# Where should we write the GIF?
Output demo_main.gif

Source demo_base.tape

# vhs doesnt source our bashrc so lets run bash here so that it will source it
Type "clear && bash"
Enter

Show

Type "echo long command here abcdefghijklmnopqrstuvwwxyz"
Sleep 1000ms
Left 5
Sleep 1000ms
Right 5
Enter

# Pause for dramatic effect...
Sleep 100ms

Type "echo"
Sleep 1500ms
Ctrl+R
Sleep 1000ms
Down
Sleep 1000ms
Down
Sleep 1000ms
Up
Sleep 1000ms

Enter

# Admire the output for a bit.
Sleep 2s
