use crate::{Arg, Command};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum HelpFormat {
    /// Output generated by clap (Rust).
    Clap,
    /// Output generated by Python's argparse module.
    Argparse,
    /// Unknown or generic format.
    Generic,
}

fn detect_format(help: &str) -> HelpFormat {
    let help_lower = help.to_lowercase();
    let has_usage = help.contains("Usage:") || help.contains("USAGE");
    let has_commands_section = help.contains("\nCommands:\n")
        || help.contains("\nSubcommands:\n")
        || help_lower.contains("commands:")
        || help_lower.contains("subcommands:")
        || help_lower.contains("commands\n")
        || help_lower.contains("commands:\n");
    let has_positional = help.lines().any(|l| {
        let t = l.trim();
        t == "positional arguments:" || t == "arguments:"
    });
    let has_optional = help.lines().any(|l| {
        let t = l.trim();
        t == "optional arguments:" || t == "options:" || t.starts_with("named arguments:")
    });

    if has_positional || (has_optional && !has_commands_section) {
        // Pure argparse output never has a "Commands:" section.
        HelpFormat::Argparse
    } else if has_usage || has_commands_section {
        HelpFormat::Clap
    } else {
        HelpFormat::Generic
    }
}

fn strip_ansi(s: &str) -> String {
    let mut result = String::with_capacity(s.len());
    let mut chars = s.chars().peekable();
    while let Some(c) = chars.next() {
        if c == '\x1b' {
            if chars.peek() == Some(&'[') {
                chars.next(); // consume '['
                while let Some(next_c) = chars.next() {
                    if next_c.is_ascii_alphabetic() {
                        break;
                    }
                }
            }
        } else {
            result.push(c);
        }
    }
    result
}

/// Parse a `--help` string into a [`Command`] with the best fidelity possible.
///
/// The function auto-detects whether the string was produced by clap,
/// Python argparse, or an unknown tool, and dispatches accordingly.
pub fn parse_help(help: &str) -> Command {
    let clean_help = strip_ansi(help);

    // Special parser for ip-style help text
    if clean_help.contains("where  OBJECT :=") || clean_help.contains("OBJECT :=") {
        let mut cmd = Command::default();
        cmd.name = Some("ip".to_string());

        // Extract OBJECTs
        if let Some(start_pos) = clean_help.find("OBJECT := {") {
            if let Some(end_pos) = clean_help[start_pos..].find('}') {
                let objects_str = &clean_help[start_pos + "OBJECT := {".len()..start_pos + end_pos];
                for obj in objects_str.split('|') {
                    let name = obj.trim().to_string();
                    if !name.is_empty() {
                        cmd.subcommands.push(Command {
                            name: Some(name),
                            ..Command::default()
                        });
                    }
                }
            }
        }

        // Extract OPTIONS
        if let Some(start_pos) = clean_help.find("OPTIONS := {") {
            if let Some(end_pos) = clean_help[start_pos..].find('}') {
                let options_str =
                    &clean_help[start_pos + "OPTIONS := {".len()..start_pos + end_pos];
                for opt in options_str.split('|') {
                    let opt_trimmed = opt.trim();
                    if opt_trimmed.starts_with('-') {
                        let clean_opt = if let Some(bracket_pos) = opt_trimmed.find('[') {
                            &opt_trimmed[..bracket_pos]
                        } else {
                            opt_trimmed
                        };
                        let clean_opt = clean_opt.split_whitespace().next().unwrap_or(clean_opt);
                        if clean_opt.starts_with("--") {
                            cmd.args.push(Arg {
                                long: Some(clean_opt.to_string()),
                                ..Arg::default()
                            });
                        } else if clean_opt.starts_with('-') {
                            cmd.args.push(Arg {
                                short: Some(clean_opt.to_string()),
                                ..Arg::default()
                            });
                        }
                    }
                }
            }
        }
        return cmd;
    }

    let mut cmd = match detect_format(&clean_help) {
        HelpFormat::Clap => parse_help_clap(&clean_help),
        HelpFormat::Argparse => parse_help_argparse(&clean_help),
        HelpFormat::Generic => parse_help_generic(&clean_help),
    };
    // Expand bracketed negation flags (like --[no-]color) into both variants
    cmd.expand_no_options();
    cmd.populate_possible_values();
    cmd
}

/// Leading-space count for a line (tabs count as 1).
fn indent_of(line: &str) -> usize {
    line.chars().take_while(|c| *c == ' ' || *c == '\t').count()
}

/// Try to parse a flag token like `-v`, `--verbose`, or `--output <FILE>`.
/// Returns `(short, long, value_name)`.
#[cfg_attr(not(test), allow(dead_code))]
pub(crate) fn parse_flag_tokens(token: &str) -> (Option<String>, Option<String>, Option<String>) {
    // Split on commas / whitespace to handle "-v, --verbose <FILE>"
    let mut short = None;
    let mut long = None;
    let mut value_name = None;

    // Tokenise: split on ", " first, then whitespace
    let pieces: Vec<&str> = token.split_whitespace().collect();
    for piece in &pieces {
        if piece.starts_with("--") {
            // May be "--flag" or "--flag=<VAL>"
            if let Some((flag, val)) = piece.split_once('=') {
                long = Some(flag.trim_end_matches(',').trim_end_matches('.').to_string());
                value_name = Some(val.trim_matches(|c| c == '<' || c == '>').to_string());
            } else {
                let mut l = piece.trim_end_matches(',').to_string();
                while l.ends_with('.') {
                    l.pop();
                }
                long = Some(l);
            }
        } else if let Some(short_candidate) = piece.strip_prefix('-') {
            let short_candidate = short_candidate.trim_end_matches(',');
            // Only treat single-character forms like `-v` as clap short flags.
            // Multi-character forms such as `-wk`, `-wK`, or `-U[dlexhi]` are
            // command-specific syntax, not plain one-letter short options.
            // We also allow forms ending with '#' (like `-T#` or `-b#`).
            let count = short_candidate.chars().count();
            if count == 1 || (count == 2 && short_candidate.ends_with('#')) {
                short = Some(format!("-{short_candidate}"));
            }
        } else if piece.starts_with('<') || piece.starts_with('[') {
            // Meta-variable — only capture the first one found so that description
            // text like `[default: 10]` does not overwrite an already-parsed hint.
            // Subsequent bracketed tokens (e.g. `[boolean]`, `[default: …]`) are
            // intentionally ignored once a value-type has been established.
            if value_name.is_none() {
                value_name = Some(
                    piece
                        .trim_matches(|c| c == '<' || c == '>' || c == '[' || c == ']')
                        .to_string(),
                );
            }
        } else if value_name.is_none()
            && !piece.is_empty()
            && (piece.chars().all(|c| {
                c.is_uppercase()
                    || c == '_'
                    || c == '-'
                    || c == '#'
                    || c == '|'
                    || c == '{'
                    || c == '}'
            }))
        {
            let clean = piece.trim_end_matches(',');
            value_name = Some(clean.to_string());
        }
    }
    (short, long, value_name)
}

/// Collect continuation lines: lines whose indent > `base_indent` (or blank).
/// Returns the combined description string.
fn collect_continuation<'a>(
    lines: &'a [&'a str],
    start: usize,
    base_indent: usize,
) -> (String, usize) {
    let mut desc_parts = Vec::new();
    let mut i = start;
    while i < lines.len() {
        let line = lines[i];
        if line.trim().is_empty() {
            let mut next_is_continuation = false;
            let mut j = i + 1;
            while j < lines.len() {
                let next_line = lines[j];
                if next_line.trim().is_empty() {
                    j += 1;
                    continue;
                }
                let ind = indent_of(next_line);
                if ind > base_indent && !next_line.trim().starts_with('-') {
                    next_is_continuation = true;
                }
                break;
            }
            if next_is_continuation {
                i = j;
                continue;
            } else {
                break;
            }
        }
        let ind = indent_of(line);
        if ind <= base_indent {
            break;
        }
        // A deeper-indented line that starts with `-` is another flag entry,
        // not description text. This handles tools like cargo that mix indent
        // levels within a single Options section.
        if line.trim().starts_with('-') {
            break;
        }
        desc_parts.push(line.trim().to_string());
        i += 1;
    }
    (desc_parts.join(" "), i)
}

/// Parse clap-style `--help` output.
pub fn parse_help_clap(help: &str) -> Command {
    let lines: Vec<&str> = help.lines().collect();
    let mut cmd = Command::default();

    if let Some(usage_pos) = lines
        .iter()
        .position(|l| l.trim_start().starts_with("Usage:"))
    {
        let after = lines[usage_pos].trim_start_matches(|c: char| c.is_whitespace());
        let after = after.strip_prefix("Usage:").unwrap_or(after).trim();
        if let Some(name_part) = after.split_whitespace().next() {
            cmd.name = Some(name_part.to_string());
        } else {
            for next_line in &lines[usage_pos + 1..] {
                let t = next_line.trim();
                if !t.is_empty() {
                    if let Some(name_part) = t.split_whitespace().next() {
                        cmd.name = Some(name_part.to_string());
                    }
                    break;
                }
            }
        }
    }

    let usage_pos = lines
        .iter()
        .position(|l| l.trim_start().starts_with("Usage:"))
        .unwrap_or(0);
    for line in &lines[..usage_pos] {
        let t = line.trim();
        if !t.is_empty() {
            let is_header = t.starts_with("***")
                || t.contains(" version ")
                || t.contains(" v1.")
                || t.contains(" v2.")
                || t.contains(" v0.")
                || t.contains("by ")
                || t.contains("Copyright");
            if !is_header {
                cmd.description = Some(t.to_string());
                break;
            }
        }
    }

    let mut i = 0;
    while i < lines.len() {
        let trimmed = lines[i].trim();

        let lower = trimmed.to_lowercase();
        let is_commands_section = trimmed == "Commands:"
            || trimmed == "Subcommands:"
            || trimmed == "Available Commands:"
            || (lower.contains("commands")
                && (trimmed.ends_with(':')
                    || lower.contains("commands are")
                    || (trimmed
                        .chars()
                        .all(|c| c.is_uppercase() || c.is_whitespace() || c == '-')
                        && !trimmed.is_empty())));

        if is_commands_section {
            i += 1;
            while i < lines.len() && lines[i].trim().is_empty() {
                i += 1;
            }
            let mut first_indent = None;
            while i < lines.len() {
                let line = lines[i];
                if line.trim().is_empty() {
                    let mut has_more = false;
                    for next_line in &lines[i + 1..] {
                        let trimmed_next = next_line.trim();
                        if trimmed_next.is_empty() {
                            continue;
                        }
                        if indent_of(next_line) > 0 {
                            has_more = true;
                        }
                        break;
                    }
                    if !has_more {
                        i += 1;
                        break;
                    } else {
                        i += 1;
                        continue;
                    }
                }
                if indent_of(line) == 0 && !line.trim().is_empty() {
                    break;
                }
                let indent = indent_of(line);
                if first_indent.is_none() {
                    first_indent = Some(indent);
                } else if Some(indent) != first_indent {
                    i += 1;
                    continue;
                }
                let trimmed_line = line.trim();
                let mut parts = trimmed_line.splitn(2, "  ");
                let sub_names_part = parts.next().unwrap_or("").trim();
                let sub_desc = parts.next().map(|s| s.trim().to_string());
                if !sub_names_part.is_empty() {
                    let name_parts: Vec<String> = sub_names_part
                        .split(',')
                        .map(|s| s.trim().to_string())
                        .collect();
                    if let Some(first_name) = name_parts.first() {
                        if !first_name.is_empty() {
                            let mut first_name_clean = first_name.trim_end_matches(':').to_string();
                            let mut sub_desc = sub_desc;
                            if first_name_clean.contains(" - ") {
                                let (name, desc) = {
                                    let mut parts = first_name_clean.splitn(2, " - ");
                                    let name = parts.next().unwrap().trim().to_string();
                                    let desc = parts.next().map(|s| s.trim().to_string());
                                    (name, desc)
                                };
                                first_name_clean = name;
                                if sub_desc.is_none() {
                                    sub_desc = desc;
                                }
                            }
                            if let Some(space_pos) = first_name_clean
                                .find(|c: char| c.is_whitespace() || c == '<' || c == '[')
                            {
                                first_name_clean = first_name_clean[..space_pos].trim().to_string();
                            }
                            if first_name_clean != "..." && !first_name_clean.is_empty() {
                                if sub_desc.is_none() && name_parts.len() > 1 {
                                    // Treat all comma-separated names as separate subcommands (e.g. npm)
                                    cmd.subcommands.push(Command {
                                        name: Some(first_name_clean),
                                        ..Command::default()
                                    });
                                    for alias in name_parts.iter().skip(1) {
                                        let mut alias_clean =
                                            alias.trim_end_matches(':').to_string();
                                        if alias_clean.contains(" - ") {
                                            let mut parts = alias_clean.splitn(2, " - ");
                                            alias_clean = parts.next().unwrap().trim().to_string();
                                        }
                                        if let Some(space_pos) = alias_clean.find(|c: char| {
                                            c.is_whitespace() || c == '<' || c == '['
                                        }) {
                                            alias_clean =
                                                alias_clean[..space_pos].trim().to_string();
                                        }
                                        if !alias_clean.is_empty() {
                                            cmd.subcommands.push(Command {
                                                name: Some(alias_clean),
                                                ..Command::default()
                                            });
                                        }
                                    }
                                } else {
                                    let aliases: Vec<String> = name_parts
                                        .iter()
                                        .skip(1)
                                        .filter(|s| !s.is_empty())
                                        .map(|s| {
                                            let mut a = s.trim_end_matches(':').to_string();
                                            if a.contains(" - ") {
                                                if let Some(first) = a.split(" - ").next() {
                                                    a = first.trim().to_string();
                                                }
                                            }
                                            if let Some(space_pos) = a.find(|c: char| {
                                                c.is_whitespace() || c == '<' || c == '['
                                            }) {
                                                a = a[..space_pos].trim().to_string();
                                            }
                                            a
                                        })
                                        .filter(|s| !s.is_empty())
                                        .collect();
                                    cmd.subcommands.push(Command {
                                        name: Some(first_name_clean),
                                        aliases,
                                        description: sub_desc,
                                        ..Command::default()
                                    });
                                }
                            }
                        }
                    }
                }
                i += 1;
            }
            continue;
        }

        let is_options_section = (trimmed.ends_with(':')
            || (trimmed
                .chars()
                .all(|c| c.is_uppercase() || c.is_whitespace() || c == '-')
                && !trimmed.is_empty()))
            && {
                let lower = trimmed.to_lowercase();
                lower.contains("options")
                    || lower.contains("flags")
                    || lower.contains("arguments")
                    || lower.contains("args")
                    || lower.contains("builder")
                    || lower.contains("parameters")
                    || lower.contains("settings")
            };

        if is_options_section {
            i += 1;
            while i < lines.len() {
                let line = lines[i];
                if line.trim().is_empty() {
                    i += 1;
                    continue;
                }
                if indent_of(line) == 0 {
                    break;
                }
                let flag_indent = indent_of(line);
                let flag_part = line.trim();

                if !flag_part.starts_with('-') && !flag_part.starts_with('[') {
                    i += 1;
                    continue;
                }

                let token_part = flag_part
                    .find("  ")
                    .map(|pos| &flag_part[..pos])
                    .unwrap_or(flag_part);
                let (short, long, value_name) = parse_flag_tokens(token_part);

                let inline_desc: Option<String> = flag_part.find("  ").and_then(|pos| {
                    let d = flag_part[pos..].trim();
                    if d.is_empty() {
                        None
                    } else {
                        Some(d.to_string())
                    }
                });
                let (cont_desc, next_i) = collect_continuation(&lines, i + 1, flag_indent);
                i = next_i;

                let description = match (inline_desc, cont_desc.as_str()) {
                    (Some(d), "") => Some(d),
                    (None, d) if !d.is_empty() => Some(d.to_string()),
                    (Some(d), rest) => Some(format!("{} {}", d, rest)),
                    (None, _) => None,
                };

                let num_args = if value_name.is_some() {
                    Some("1".to_string())
                } else {
                    None
                };

                cmd.args.push(Arg {
                    short,
                    long,
                    description,
                    value_name,
                    num_args,
                    ..Default::default()
                });
            }
            continue;
        }

        i += 1;
    }

    cmd
}

/// Parse Python argparse-style `--help` output.
pub fn parse_help_argparse(help: &str) -> Command {
    let lines: Vec<&str> = help.lines().collect();
    let mut cmd = Command::default();

    if let Some(usage_line) = lines
        .iter()
        .find(|l| l.trim_start().to_lowercase().starts_with("usage:"))
    {
        let after = usage_line
            .trim_start_matches(|c: char| c.is_whitespace())
            .to_lowercase();
        let after = after.strip_prefix("usage:").unwrap_or(&after).trim();
        if let Some(name) = after.split_whitespace().next() {
            cmd.name = Some(name.to_string());
        }
    }

    let usage_pos = lines
        .iter()
        .position(|l| l.trim_start().to_lowercase().starts_with("usage:"))
        .unwrap_or(0);
    let mut found_blank = false;
    for line in &lines[usage_pos + 1..] {
        if line.trim().is_empty() {
            found_blank = true;
        } else if found_blank {
            let t = line.trim();
            if !t.ends_with(':') {
                cmd.description = Some(t.to_string());
            }
            break;
        }
    }

    let mut i = 0;
    while i < lines.len() {
        let trimmed = lines[i].trim();

        let is_args_section = trimmed == "positional arguments:"
            || trimmed == "optional arguments:"
            || trimmed == "options:"
            || trimmed.starts_with("named arguments:");

        if is_args_section {
            i += 1;
            while i < lines.len() {
                let line = lines[i];
                if line.trim().is_empty() {
                    i += 1;
                    break;
                }
                if indent_of(line) == 0 && line.trim().ends_with(':') {
                    break;
                }
                let flag_indent = indent_of(line);
                let flag_part = line.trim();

                let (short, long, value_name) = if flag_part.starts_with('-') {
                    let token_part = flag_part
                        .find("  ")
                        .map(|pos| &flag_part[..pos])
                        .unwrap_or(flag_part);
                    parse_flag_tokens(token_part)
                } else {
                    let name_token = flag_part.split_whitespace().next().unwrap_or("");
                    (None, Some(name_token.to_string()), None)
                };

                let inline_desc: Option<String> = if let Some(pos) = flag_part.find("  ") {
                    let d = flag_part[pos..].trim();
                    if !d.is_empty() {
                        Some(d.to_string())
                    } else {
                        None
                    }
                } else {
                    None
                };

                let (cont_desc, next_i) = collect_continuation(&lines, i + 1, flag_indent);
                i = next_i;

                let description = match (inline_desc, cont_desc.as_str()) {
                    (Some(d), "") => Some(d),
                    (None, d) if !d.is_empty() => Some(d.to_string()),
                    (Some(d), rest) => Some(format!("{} {}", d, rest)),
                    (None, _) => None,
                };

                let num_args = if value_name.is_some() {
                    Some("1".to_string())
                } else {
                    None
                };

                cmd.args.push(Arg {
                    short,
                    long,
                    description,
                    value_name,
                    num_args,
                    ..Default::default()
                });
            }
            continue;
        }

        i += 1;
    }

    cmd
}

/// Fallback parser for unrecognised help formats.
pub fn parse_help_generic(help: &str) -> Command {
    let lines: Vec<&str> = help.lines().collect();
    let mut cmd = Command::default();

    for line in &lines {
        let lower = line.trim().to_lowercase();
        if lower.starts_with("usage:") {
            let after = line
                .trim()
                .trim_start_matches(|c: char| c.is_alphabetic() || c == ':')
                .trim();
            if let Some(name) = after.split_whitespace().next() {
                cmd.name = Some(name.to_string());
                break;
            }
        }
    }

    for line in &lines {
        let t = line.trim();
        if !t.is_empty() && !t.starts_with('-') && !t.to_lowercase().starts_with("usage:") {
            cmd.description = Some(t.to_string());
            break;
        }
    }

    let mut i = 0;
    while i < lines.len() {
        let line = lines[i];
        let flag_part = line.trim();

        if flag_part.starts_with('-') {
            let flag_indent = indent_of(line);
            let token_part = flag_part
                .find("  ")
                .map(|pos| &flag_part[..pos])
                .unwrap_or(flag_part);
            let (short, long, value_name) = parse_flag_tokens(token_part);

            let inline_desc: Option<String> = if let Some(pos) = flag_part.find("  ") {
                let d = flag_part[pos..].trim();
                if !d.is_empty() {
                    Some(d.to_string())
                } else {
                    None
                }
            } else {
                None
            };

            let (cont_desc, next_i) = collect_continuation(&lines, i + 1, flag_indent);
            i = next_i;

            let description = match (inline_desc, cont_desc.as_str()) {
                (Some(d), "") => Some(d),
                (None, d) if !d.is_empty() => Some(d.to_string()),
                (Some(d), rest) => Some(format!("{} {}", d, rest)),
                (None, _) => None,
            };

            let num_args = if value_name.is_some() {
                Some("1".to_string())
            } else {
                None
            };

            cmd.args.push(Arg {
                short,
                long,
                description,
                value_name,
                num_args,
                ..Default::default()
            });
            continue;
        }

        i += 1;
    }

    cmd
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_helpers::*;
    use crate::{SynthesisStrategy, ValueHint, synthesize_completion};

    fn long_names(cmd: &Command) -> Vec<&str> {
        cmd.args.iter().filter_map(|a| a.long.as_deref()).collect()
    }

    fn short_names(cmd: &Command) -> Vec<&str> {
        cmd.args.iter().filter_map(|a| a.short.as_deref()).collect()
    }

    fn subcommand_names(cmd: &Command) -> Vec<&str> {
        cmd.subcommands
            .iter()
            .filter_map(|s| s.name.as_deref())
            .collect()
    }

    fn arg_by_long<'a>(cmd: &'a Command, long: &str) -> Option<&'a Arg> {
        cmd.args.iter().find(|a| a.long.as_deref() == Some(long))
    }

    fn arg_by_short<'a>(cmd: &'a Command, short: &str) -> Option<&'a Arg> {
        cmd.args.iter().find(|a| a.short.as_deref() == Some(short))
    }

    fn subcommand_by_name<'a>(cmd: &'a Command, name: &str) -> Option<&'a Command> {
        cmd.subcommands
            .iter()
            .find(|s| s.name.as_deref() == Some(name))
    }

    #[test]
    fn test_flyline_help_clap() {
        let cmd = parse_help(&read_fixture(&["flyline"]));
        assert_eq!(cmd.name.as_deref(), Some("flyline"));

        assert_contains_subcommands(
            &cmd,
            &[
                ("set-agent-mode", "Configure AI agent mode."),
                ("dump-logs", "Dump in-memory logs to file."),
                (
                    "stream-logs",
                    "Dump current logs to PATH and append new logs.",
                ),
                (
                    "run-tutorial",
                    "Run the interactive tutorial for first-time users.",
                ),
            ],
        );

        assert_contains_expected_args(
            &cmd,
            &[
                ExpectedArg {
                    arg: Arg {
                        long: Some("--version".to_string()),
                        ..Default::default()
                    },
                    description_contains: "Show version information",
                },
                ExpectedArg {
                    arg: Arg {
                        long: Some("--log-level".to_string()),
                        value_name: Some("LEVEL".to_string()),
                        num_args: Some("1".to_string()),
                        value_enum: Some(vec![
                            "error".to_string(),
                            "warn".to_string(),
                            "info".to_string(),
                            "debug".to_string(),
                            "trace".to_string(),
                        ]),
                        ..Default::default()
                    },
                    description_contains: "logging level",
                },
                ExpectedArg {
                    arg: Arg {
                        long: Some("--show-animations".to_string()),
                        value_name: Some("SHOW_ANIMATIONS".to_string()),
                        num_args: Some("1".to_string()),
                        value_enum: Some(vec!["true".to_string(), "false".to_string()]),
                        ..Default::default()
                    },
                    description_contains: "",
                },
                ExpectedArg {
                    arg: Arg {
                        long: Some("--show-inline-history".to_string()),
                        value_name: Some("SHOW_INLINE_HISTORY".to_string()),
                        num_args: Some("1".to_string()),
                        value_enum: Some(vec!["true".to_string(), "false".to_string()]),
                        ..Default::default()
                    },
                    description_contains: "",
                },
                ExpectedArg {
                    arg: Arg {
                        long: Some("--auto-close-chars".to_string()),
                        value_name: Some("AUTO_CLOSE_CHARS".to_string()),
                        num_args: Some("1".to_string()),
                        value_enum: Some(vec!["true".to_string(), "false".to_string()]),
                        ..Default::default()
                    },
                    description_contains: "",
                },
                ExpectedArg {
                    arg: Arg {
                        long: Some("--enable-extended-key-codes".to_string()),
                        value_name: Some("ENABLE_EXTENDED_KEY_CODES".to_string()),
                        num_args: Some("1".to_string()),
                        value_enum: Some(vec!["true".to_string(), "false".to_string()]),
                        ..Default::default()
                    },
                    description_contains: "",
                },
            ],
        );
    }

    #[test]
    fn test_flyline_create_anim_help_clap() {
        let cmd = parse_help(&read_fixture(&["flyline", "create-anim"]));
        assert_eq!(cmd.name.as_deref(), Some("flyline"));
        assert!(
            cmd.description
                .as_deref()
                .unwrap_or("")
                .contains("animation")
        );

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--name"));
        assert!(longs.contains(&"--fps"));
        assert!(longs.contains(&"--ping-pong"));
        assert!(longs.contains(&"--help"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-h"));

        assert_eq!(
            arg_by_long(&cmd, "--name").and_then(|a| a.value_name.as_deref()),
            Some("NAME")
        );
        assert_eq!(
            arg_by_long(&cmd, "--name").map(|a| a.value_hint),
            Some(ValueHint::Unknown)
        );
        assert_eq!(
            arg_by_long(&cmd, "--fps").and_then(|a| a.value_name.as_deref()),
            Some("FPS")
        );
        assert_eq!(
            arg_by_long(&cmd, "--fps").map(|a| a.value_hint),
            Some(ValueHint::Unknown)
        );

        assert!(
            arg_by_long(&cmd, "--name")
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("animation placeholder")
        );
        assert!(
            arg_by_long(&cmd, "--fps")
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("frames per second")
        );
        assert!(
            arg_by_long(&cmd, "--ping-pong")
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("Reverse direction")
        );
    }

    #[test]
    fn test_cargo_help_clap() {
        let cmd = parse_help(&read_fixture(&["cargo"]));
        assert_eq!(cmd.name.as_deref(), Some("cargo"));

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--version"));
        assert!(longs.contains(&"--verbose"));
        assert!(longs.contains(&"--quiet"));
        assert!(longs.contains(&"--explain"));
        assert!(longs.contains(&"--color"));
        assert!(longs.contains(&"--help"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-V"));
        assert!(shorts.contains(&"-v"));
        assert!(shorts.contains(&"-h"));

        assert_eq!(
            arg_by_long(&cmd, "--explain").and_then(|a| a.value_name.as_deref()),
            Some("CODE")
        );
        assert_eq!(
            arg_by_long(&cmd, "--explain").map(|a| a.value_hint),
            Some(ValueHint::Unknown)
        );
        assert_eq!(
            arg_by_long(&cmd, "--color").and_then(|a| a.value_name.as_deref()),
            Some("WHEN")
        );
        assert_eq!(
            arg_by_long(&cmd, "--color").map(|a| a.value_hint),
            Some(ValueHint::Unknown)
        );

        let subs = subcommand_names(&cmd);
        assert!(subs.contains(&"build"));
        assert!(subs.contains(&"check"));
        assert!(subs.contains(&"clean"));

        let build_sub = subcommand_by_name(&cmd, "build").unwrap();
        assert_eq!(build_sub.aliases, vec!["b".to_string()]);
        assert_eq!(
            build_sub.description.as_deref(),
            Some("Compile the current package")
        );

        let check_sub = subcommand_by_name(&cmd, "check").unwrap();
        assert_eq!(check_sub.aliases, vec!["c".to_string()]);
        assert_eq!(
            check_sub.description.as_deref(),
            Some("Analyze the current package and report errors, but don't build object files")
        );
    }

    #[test]
    fn test_python_help_generic() {
        let cmd = parse_help(&read_fixture(&["python"]));
        assert_eq!(cmd.name.as_deref(), Some("python3"));

        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-h"));
        assert!(shorts.contains(&"-v"));
        assert!(shorts.contains(&"-V"));
        assert!(shorts.contains(&"-q"));

        assert!(
            cmd.args
                .iter()
                .find(|a| a.short.as_deref() == Some("-h"))
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("help message")
        );
    }

    #[test]
    fn test_argparse_example() {
        let cmd = parse_help(&read_fixture(&["argparse_example"]));
        assert_eq!(cmd.name.as_deref(), Some("prog.py"));
        assert!(
            cmd.description
                .as_deref()
                .unwrap_or("")
                .contains("argparse")
        );

        let longs = long_names(&cmd);
        assert!(longs.contains(&"bar"));
        assert!(longs.contains(&"--foo"));
        assert!(longs.contains(&"--help"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-h"));

        assert!(
            arg_by_long(&cmd, "bar")
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("bar argument")
        );
        assert!(
            arg_by_long(&cmd, "--foo")
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("foo value")
        );
    }

    #[test]
    fn test_argparse_subparsers() {
        let cmd = parse_help(&read_fixture(&["argparse_subparsers"]));
        assert_eq!(cmd.name.as_deref(), Some("myapp"));
        assert!(cmd.description.as_deref().unwrap_or("").contains("My"));

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--help"));
        assert!(longs.contains(&"--verbose"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-h"));

        assert!(
            arg_by_long(&cmd, "--verbose")
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("verbose output")
        );
    }

    #[test]
    fn test_click_help() {
        let cmd = parse_help(&read_fixture(&["click"]));
        assert_eq!(cmd.name.as_deref(), Some("cli"));

        let subs = subcommand_names(&cmd);
        assert!(subs.contains(&"hello"));
        assert!(subs.contains(&"goodbye"));
        assert_eq!(
            subcommand_by_name(&cmd, "hello").and_then(|s| s.description.as_deref()),
            Some("Greet someone.")
        );
        assert_eq!(
            subcommand_by_name(&cmd, "goodbye").and_then(|s| s.description.as_deref()),
            Some("Say goodbye.")
        );

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--name"));
        assert!(longs.contains(&"--count"));
        assert!(longs.contains(&"--verbose"));
        assert!(longs.contains(&"--help"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-v"));
    }

    #[test]
    fn test_argh_help() {
        let cmd = parse_help(&read_fixture(&["argh"]));
        assert_eq!(cmd.name.as_deref(), Some("myapp"));
        assert!(cmd.description.as_deref().unwrap_or("").contains("argh"));

        let longs = long_names(&cmd);
        assert!(longs.contains(&"name"));
        assert!(longs.contains(&"--help"));
        assert!(longs.contains(&"--verbose"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-h"));

        assert!(
            arg_by_long(&cmd, "name")
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("name argument")
        );
        assert!(
            arg_by_long(&cmd, "--verbose")
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("verbose output")
        );
    }

    #[test]
    fn test_yargs_help() {
        let cmd = parse_help(&read_fixture(&["yargs"]));
        let subs = subcommand_names(&cmd);
        assert!(subs.contains(&"serve"));
        assert!(subs.contains(&"build"));
        assert!(subs.contains(&"test"));

        assert!(
            subcommand_by_name(&cmd, "serve")
                .and_then(|s| s.description.as_deref())
                .unwrap_or("")
                .contains("development server")
        );
        assert!(
            subcommand_by_name(&cmd, "build")
                .and_then(|s| s.description.as_deref())
                .unwrap_or("")
                .contains("production")
        );

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--help"));
        assert!(longs.contains(&"--version"));
        assert!(longs.contains(&"--port"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-p"));
    }

    #[test]
    fn test_commander_help() {
        let cmd = parse_help(&read_fixture(&["commander"]));
        assert_eq!(cmd.name.as_deref(), Some("program"));

        let subs = subcommand_names(&cmd);
        assert!(subs.contains(&"start"));
        assert!(subs.contains(&"stop"));
        assert!(subs.contains(&"status"));
        assert_eq!(
            subcommand_by_name(&cmd, "start").and_then(|s| s.description.as_deref()),
            Some("Start the server")
        );
        assert_eq!(
            subcommand_by_name(&cmd, "stop").and_then(|s| s.description.as_deref()),
            Some("Stop the server")
        );

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--version"));
        assert!(longs.contains(&"--help"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-V"));
        assert!(shorts.contains(&"-h"));
    }

    #[test]
    fn test_cobra_help() {
        let cmd = parse_help(&read_fixture(&["cobra"]));
        assert_eq!(cmd.name.as_deref(), Some("myapp"));
        assert!(
            cmd.description
                .as_deref()
                .unwrap_or("")
                .contains("application")
        );

        let subs = subcommand_names(&cmd);
        assert!(subs.contains(&"serve"));
        assert!(subs.contains(&"version"));
        assert_eq!(
            subcommand_by_name(&cmd, "serve").and_then(|s| s.description.as_deref()),
            Some("Start the server")
        );
        assert!(
            subcommand_by_name(&cmd, "completion")
                .and_then(|s| s.description.as_deref())
                .unwrap_or("")
                .contains("autocompletion")
        );

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--help"));
        assert!(longs.contains(&"--toggle"));
        assert!(longs.contains(&"--config"));
        assert!(longs.contains(&"--log-level"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-h"));
        assert!(shorts.contains(&"-t"));
    }

    #[test]
    fn test_docopt_help() {
        let cmd = parse_help(&read_fixture(&["docopt"]));
        assert_eq!(cmd.name.as_deref(), Some("naval_fate"));

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--help"));
        assert!(longs.contains(&"--version"));
        assert!(longs.contains(&"--speed"));
        assert!(longs.contains(&"--moored"));
        assert!(longs.contains(&"--drifting"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-h"));

        assert_eq!(
            arg_by_long(&cmd, "--speed").and_then(|a| a.value_name.as_deref()),
            Some("kn")
        );
        assert_eq!(
            arg_by_long(&cmd, "--speed").map(|a| a.value_hint),
            Some(ValueHint::Unknown)
        );
    }

    #[test]
    fn test_git_help() {
        let cmd = parse_help(&read_fixture(&["git"]));
        assert_eq!(cmd.name.as_deref(), Some("git"));

        let subs = subcommand_names(&cmd);
        assert!(subs.contains(&"clone"));
        assert!(subs.contains(&"commit"));
        assert!(subs.contains(&"log"));
        assert!(subs.contains(&"diff"));
        assert!(subs.contains(&"push"));
        assert!(subs.contains(&"pull"));
        assert!(subs.contains(&"branch"));
        assert!(subs.contains(&"status"));

        assert_eq!(
            subcommand_by_name(&cmd, "clone").and_then(|s| s.description.as_deref()),
            Some("Clone a repository into a new directory")
        );
        assert_eq!(
            subcommand_by_name(&cmd, "commit").and_then(|s| s.description.as_deref()),
            Some("Record changes to the repository")
        );
    }

    #[test]
    fn test_git_log_help() {
        let cmd = parse_help(&read_fixture(&["git", "log"]));
        assert_eq!(cmd.name.as_deref(), Some("git"));

        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-q"));
        assert!(shorts.contains(&"-v"));
        assert!(shorts.contains(&"-n"));
        assert!(shorts.contains(&"-p"));
        assert!(shorts.contains(&"-s"));
        assert!(shorts.contains(&"-i"));

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--max-count"));
        assert!(longs.contains(&"--since"));
        assert!(longs.contains(&"--author"));
        assert!(longs.contains(&"--grep"));
        assert!(longs.contains(&"--oneline"));
        assert!(longs.contains(&"--graph"));
        assert!(longs.contains(&"--stat"));
        assert!(longs.contains(&"--first-parent"));
        assert!(longs.contains(&"--patch"));
        assert!(longs.contains(&"--no-patch"));

        assert_eq!(
            arg_by_long(&cmd, "--max-count").and_then(|a| a.value_name.as_deref()),
            Some("n")
        );
        assert_eq!(
            arg_by_long(&cmd, "--max-count").map(|a| a.value_hint),
            Some(ValueHint::Unknown)
        );
        assert_eq!(
            arg_by_long(&cmd, "--since").and_then(|a| a.value_name.as_deref()),
            Some("date")
        );
        assert_eq!(
            arg_by_long(&cmd, "--since").map(|a| a.value_hint),
            Some(ValueHint::Unknown)
        );
        assert_eq!(
            arg_by_long(&cmd, "--author").and_then(|a| a.value_name.as_deref()),
            Some("pattern")
        );
        assert_eq!(
            arg_by_long(&cmd, "--author").map(|a| a.value_hint),
            Some(ValueHint::Unknown)
        );

        assert!(
            arg_by_long(&cmd, "--graph")
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("ASCII")
        );
    }

    #[test]
    fn test_git_commit_help() {
        let cmd = parse_help(&read_fixture(&["git", "commit"]));
        assert_eq!(cmd.name.as_deref(), Some("git"));

        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-q"));
        assert!(shorts.contains(&"-v"));
        assert!(shorts.contains(&"-m"));
        assert!(shorts.contains(&"-a"));
        assert!(shorts.contains(&"-s"));
        assert!(shorts.contains(&"-e"));

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--message"));
        assert!(longs.contains(&"--author"));
        assert!(longs.contains(&"--amend"));
        assert!(longs.contains(&"--no-verify"));
        assert!(longs.contains(&"--allow-empty"));
        assert!(longs.contains(&"--dry-run"));
        assert!(longs.contains(&"--squash"));
        assert!(longs.contains(&"--signoff"));

        assert_eq!(
            arg_by_long(&cmd, "--message").and_then(|a| a.value_name.as_deref()),
            Some("message")
        );
        assert_eq!(
            arg_by_long(&cmd, "--message").map(|a| a.value_hint),
            Some(ValueHint::Unknown)
        );
        assert_eq!(
            arg_by_long(&cmd, "--file").and_then(|a| a.value_name.as_deref()),
            Some("file")
        );
        assert_eq!(
            arg_by_long(&cmd, "--file").map(|a| a.value_hint),
            Some(ValueHint::FilePath)
        );
    }

    #[test]
    fn test_git_diff_help() {
        let cmd = parse_help(&read_fixture(&["git", "diff"]));
        assert_eq!(cmd.name.as_deref(), Some("git"));

        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-p"));
        assert!(shorts.contains(&"-s"));
        assert!(shorts.contains(&"-U"));
        assert!(shorts.contains(&"-W"));

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--patch"));
        assert!(longs.contains(&"--no-patch"));
        assert!(longs.contains(&"--stat"));
        assert!(longs.contains(&"--name-only"));
        assert!(longs.contains(&"--cached"));
        assert!(longs.contains(&"--word-diff"));
        assert!(longs.contains(&"--color"));
        assert!(longs.contains(&"--unified"));
    }

    #[test]
    fn test_subcommand_synthesis_overlay() {
        let help_runner = |args: &[&str]| -> anyhow::Result<String> {
            let text = match args {
                [] => read_fixture(&["git"]),
                ["log"] => read_fixture(&["git", "log"]),
                ["commit"] => read_fixture(&["git", "commit"]),
                ["diff"] => read_fixture(&["git", "diff"]),
                _ => "".to_string(),
            };
            Ok(text)
        };
        let top = synthesize_completion("git", help_runner, SynthesisStrategy::RunHelp).unwrap();

        assert!(subcommand_names(&top).contains(&"log"));
        assert!(subcommand_names(&top).contains(&"commit"));

        let log_sub = subcommand_by_name(&top, "log").expect("log subcommand should exist");
        assert!(long_names(log_sub).contains(&"--oneline"));
        assert!(long_names(log_sub).contains(&"--graph"));
        assert!(long_names(log_sub).contains(&"--since"));

        let commit_sub =
            subcommand_by_name(&top, "commit").expect("commit subcommand should exist");
        assert!(long_names(commit_sub).contains(&"--amend"));
        assert!(long_names(commit_sub).contains(&"--message"));
        assert!(long_names(commit_sub).contains(&"--no-verify"));

        let diff_sub = subcommand_by_name(&top, "diff").expect("diff subcommand should exist");
        assert!(long_names(diff_sub).contains(&"--cached"));
        assert!(long_names(diff_sub).contains(&"--stat"));
    }

    const GIT_REMOTE_HELP: &str = r#"Usage: git remote [OPTIONS] <COMMAND>

Commands:
  add      Add a remote
  set-url  Changes URLs for the remote
  remove   Remove a remote
  rename   Rename a remote

Options:
  -v, --verbose    Be verbose
  -h, --help       Print help
"#;

    const GIT_REMOTE_ADD_HELP: &str = r#"usage: git remote add <name> <url>

    -f, --fetch        Fetch after adding the remote
    -t, --track <branch>
                       Track given branch
    --tags             Import all tags
    --no-tags          Do not import tags
"#;

    const GIT_REMOTE_SET_URL_HELP: &str = r#"usage: git remote set-url [--push] <name> <new-url>

    --push             Manipulate push URLs
    --add              Add URL to list
    --delete           Delete URL
"#;

    const GIT_WITH_REMOTE_HELP: &str = r#"Usage: git [OPTIONS] <COMMAND>

Commands:
  clone   Clone a repository into a new directory
  remote  Manage set of tracked repositories

Options:
  -h, --help  Print help
"#;

    #[test]
    fn test_nested_subcommand_synthesis_simulation() {
        let help_runner = |args: &[&str]| -> anyhow::Result<String> {
            let text = match args {
                [] => GIT_WITH_REMOTE_HELP,
                ["remote"] => GIT_REMOTE_HELP,
                ["remote", "add"] => GIT_REMOTE_ADD_HELP,
                ["remote", "set-url"] => GIT_REMOTE_SET_URL_HELP,
                _ => "",
            };
            Ok(text.to_string())
        };
        let top = synthesize_completion("git", help_runner, SynthesisStrategy::RunHelp).unwrap();

        let remote =
            subcommand_by_name(&top, "remote").expect("remote subcommand should be present");
        assert!(long_names(remote).contains(&"--verbose"));

        let remote_add =
            subcommand_by_name(remote, "add").expect("remote add subcommand should be present");
        assert!(long_names(remote_add).contains(&"--fetch"));
        assert!(short_names(remote_add).contains(&"-f"));
        assert_eq!(
            arg_by_long(remote_add, "--track").and_then(|a| a.value_name.as_deref()),
            Some("branch")
        );
        assert_eq!(
            arg_by_long(remote_add, "--track").map(|a| a.value_hint),
            Some(ValueHint::Unknown)
        );

        let remote_set_url = subcommand_by_name(remote, "set-url")
            .expect("remote set-url subcommand should be present");
        assert!(long_names(remote_set_url).contains(&"--push"));
        assert!(long_names(remote_set_url).contains(&"--delete"));
    }

    #[test]
    fn test_readelf_help() {
        let cmd = parse_test_help("readelf");
        assert_eq!(cmd.name.as_deref(), Some("readelf"));

        assert_contains_expected_args(
            &cmd,
            &[
                ExpectedArg {
                    arg: Arg {
                        short: Some("-a".to_string()),
                        long: Some("--all".to_string()),
                        ..Default::default()
                    },
                    description_contains: "Equivalent to",
                },
                ExpectedArg {
                    arg: Arg {
                        short: Some("-h".to_string()),
                        long: Some("--file-header".to_string()),
                        ..Default::default()
                    },
                    description_contains: "Display the ELF file header",
                },
                ExpectedArg {
                    arg: Arg {
                        short: Some("-l".to_string()),
                        long: Some("--program-headers".to_string()),
                        ..Default::default()
                    },
                    description_contains: "Display the program headers",
                },
                ExpectedArg {
                    arg: Arg {
                        short: Some("-S".to_string()),
                        long: Some("--section-headers".to_string()),
                        ..Default::default()
                    },
                    description_contains: "Display the sections' header",
                },
                ExpectedArg {
                    arg: Arg {
                        short: Some("-r".to_string()),
                        long: Some("--relocs".to_string()),
                        ..Default::default()
                    },
                    description_contains: "Display the relocations",
                },
                ExpectedArg {
                    arg: Arg {
                        short: Some("-d".to_string()),
                        long: Some("--dynamic".to_string()),
                        ..Default::default()
                    },
                    description_contains: "Display the dynamic section",
                },
                ExpectedArg {
                    arg: Arg {
                        short: Some("-n".to_string()),
                        long: Some("--notes".to_string()),
                        ..Default::default()
                    },
                    description_contains: "Display the contents of note sections",
                },
                ExpectedArg {
                    arg: Arg {
                        short: Some("-W".to_string()),
                        long: Some("--wide".to_string()),
                        ..Default::default()
                    },
                    description_contains: "Allow output width to exceed",
                },
                ExpectedArg {
                    arg: Arg {
                        short: Some("-H".to_string()),
                        long: Some("--help".to_string()),
                        ..Default::default()
                    },
                    description_contains: "Display this information",
                },
                ExpectedArg {
                    arg: Arg {
                        short: Some("-v".to_string()),
                        long: Some("--version".to_string()),
                        ..Default::default()
                    },
                    description_contains: "Display the version number",
                },
                ExpectedArg {
                    arg: Arg {
                        short: Some("-x".to_string()),
                        long: Some("--hex-dump".to_string()),
                        value_name: Some("number|name".to_string()),
                        num_args: Some("1".to_string()),
                        value_hint: ValueHint::Unknown,
                        ..Default::default()
                    },
                    description_contains: "Dump the contents of section",
                },
            ],
        );
    }

    #[test]
    fn test_parse_flag_tokens_ignores_multi_character_short_forms() {
        let (short, long, value_name) = parse_flag_tokens("-wk --debug-dump=links");
        assert_eq!(short, None);
        assert_eq!(long.as_deref(), Some("--debug-dump"));
        assert_eq!(value_name.as_deref(), Some("links"));

        let (short, long, value_name) =
            parse_flag_tokens("-U[dlexhi] --unicode=[default|locale|escape|hex|highlight|invalid]");
        assert_eq!(short, None);
        assert_eq!(long.as_deref(), Some("--unicode"));
        assert_eq!(
            value_name.as_deref(),
            Some("[default|locale|escape|hex|highlight|invalid]")
        );
    }
    #[test]
    fn test_zstd_help() {
        let cmd = parse_test_help("zstd");

        // Check overall commands info
        assert_eq!(
            cmd.description.as_deref(),
            Some(
                "Compress or decompress the INPUT file(s); reads from STDIN if INPUT is `-` or not provided."
            )
        );

        assert_contains_expected_args(
            &cmd,
            &[
                ExpectedArg {
                    arg: Arg {
                        short: Some("-o".to_string()),
                        value_name: Some("OUTPUT".to_string()),
                        num_args: Some("1".to_string()),
                        value_hint: ValueHint::FilePath,
                        ..Default::default()
                    },
                    description_contains: "Write output to a single file",
                },
                ExpectedArg {
                    arg: Arg {
                        short: Some("-k".to_string()),
                        long: Some("--keep".to_string()),
                        ..Default::default()
                    },
                    description_contains: "Preserve INPUT file(s)",
                },
                ExpectedArg {
                    arg: Arg {
                        long: Some("--rm".to_string()),
                        ..Default::default()
                    },
                    description_contains: "Remove INPUT file(s) after successful",
                },
                ExpectedArg {
                    arg: Arg {
                        short: Some("-#".to_string()),
                        ..Default::default()
                    },
                    description_contains: "Desired compression level",
                },
                ExpectedArg {
                    arg: Arg {
                        short: Some("-D".to_string()),
                        value_name: Some("DICT".to_string()),
                        num_args: Some("1".to_string()),
                        value_hint: ValueHint::FilePath,
                        ..Default::default()
                    },
                    description_contains: "Use DICT as the dictionary",
                },
                ExpectedArg {
                    arg: Arg {
                        long: Some("--trace".to_string()),
                        value_name: Some("LOG".to_string()),
                        num_args: Some("1".to_string()),
                        value_hint: ValueHint::FilePath,
                        ..Default::default()
                    },
                    description_contains: "Log tracing information to LOG",
                },
                ExpectedArg {
                    arg: Arg {
                        long: Some("--format".to_string()),
                        value_name: Some("zstd".to_string()),
                        num_args: Some("1".to_string()),
                        value_hint: ValueHint::Unknown,
                        ..Default::default()
                    },
                    description_contains: "Compress files to the",
                },
                ExpectedArg {
                    arg: Arg {
                        long: Some("--test".to_string()),
                        ..Default::default()
                    },
                    description_contains: "Test compressed file integrity",
                },
                ExpectedArg {
                    arg: Arg {
                        long: Some("--train".to_string()),
                        ..Default::default()
                    },
                    description_contains: "Create a dictionary from a training set",
                },
                ExpectedArg {
                    arg: Arg {
                        short: Some("-T#".to_string()),
                        ..Default::default()
                    },
                    description_contains: "Spawn # compression threads",
                },
            ],
        );
    }

    #[test]
    fn test_expand_no_options_in_help() {
        const HELP: &str = r#"Usage: mytool [OPTIONS]

Options:
  --[no-]color             Enable or disable color output.
  --[no]nocolor            Enable or disable nocolor option.
"#;
        let cmd = parse_help(HELP);
        let args = &cmd.args;

        // --[no-]color should expand to --color and --no-color
        assert!(args.iter().any(|a| a.long.as_deref() == Some("--color")));
        assert!(args.iter().any(|a| a.long.as_deref() == Some("--no-color")));

        // --[no]nocolor should expand to --nocolor and --nonocolor
        assert!(args.iter().any(|a| a.long.as_deref() == Some("--nocolor")));
        assert!(
            args.iter()
                .any(|a| a.long.as_deref() == Some("--nonocolor"))
        );
    }

    #[test]
    fn test_cargo_help_with_ellipsis() {
        const HELP: &str = r#"Rust's package manager

Usage: cargo [+toolchain] [OPTIONS] [COMMAND]

Options:
  -v, --verbose...               Use verbose output
  -h, --help                     Print help

Commands:
    build, b    Compile the current package
    check, c    Analyze the current package
    ...         See all commands with --list
"#;
        let cmd = parse_help(HELP);
        assert_eq!(cmd.name.as_deref(), Some("cargo"));

        // Check flags: --verbose... should become --verbose
        let verbose = cmd
            .args
            .iter()
            .find(|a| a.short.as_deref() == Some("-v"))
            .expect("verbose flag found");
        assert_eq!(verbose.long.as_deref(), Some("--verbose"));

        // Check subcommands: ... should be skipped
        let subs = subcommand_names(&cmd);
        assert!(subs.contains(&"build"));
        assert!(subs.contains(&"check"));
        assert!(!subs.contains(&"..."));
        assert_eq!(subs.len(), 2);
    }

    fn parse_test_help(name: &str) -> Command {
        let content =
            std::fs::read_to_string(format!("../tests/help_texts/{}/help.txt", name)).unwrap();
        parse_help(&content)
    }

    fn read_fixture(path: &[&str]) -> String {
        let path_str = path.join("/");
        std::fs::read_to_string(format!("../tests/help_texts/{}/help.txt", path_str)).unwrap()
    }

    #[test]
    fn test_ip_help() {
        let cmd = parse_test_help("ip");
        let subs = subcommand_names(&cmd);
        let expected_subs = vec![
            "address",
            "addrlabel",
            "amt",
            "fou",
            "help",
            "ila",
            "ioam",
            "l2tp",
            "link",
            "macsec",
            "maddress",
            "monitor",
            "mptcp",
            "mroute",
            "mrule",
            "neighbor",
            "neighbour",
            "netconf",
            "netns",
            "nexthop",
            "ntable",
            "ntbl",
            "route",
            "rule",
            "sr",
            "tap",
            "tcpmetrics",
            "token",
            "tunnel",
            "tuntap",
            "vrf",
            "xfrm",
        ];
        for sub in expected_subs {
            assert!(subs.contains(&sub), "Missing subcommand: {}", sub);
        }

        let version = arg_by_short(&cmd, "-V").unwrap();
        assert_eq!(version.long.as_deref(), None);

        let stats = arg_by_short(&cmd, "-s").unwrap();
        assert_eq!(stats.long.as_deref(), None);

        let details = arg_by_short(&cmd, "-d").unwrap();
        assert_eq!(details.long.as_deref(), None);

        let resolve = arg_by_short(&cmd, "-r").unwrap();
        assert_eq!(resolve.long.as_deref(), None);

        let pretty = arg_by_short(&cmd, "-p").unwrap();
        assert_eq!(pretty.long.as_deref(), None);
    }

    #[test]
    fn test_docker_help() {
        let cmd = parse_test_help("docker");
        let subs = subcommand_names(&cmd);
        let expected_subs = vec![
            "run", "exec", "ps", "build", "images", "pull", "push", "rm", "rmi", "logs",
        ];
        for sub in expected_subs {
            assert!(subs.contains(&sub), "Missing subcommand: {}", sub);
        }

        let config = arg_by_long(&cmd, "--config").unwrap();
        assert_eq!(config.short.as_deref(), None);
        assert_eq!(config.value_hint, ValueHint::Unknown);

        let context = arg_by_long(&cmd, "--context").unwrap();
        assert_eq!(context.short.as_deref(), Some("-c"));

        let debug = arg_by_long(&cmd, "--debug").unwrap();
        assert_eq!(debug.short.as_deref(), Some("-D"));

        let host = arg_by_long(&cmd, "--host").unwrap();
        assert_eq!(host.short.as_deref(), Some("-H"));
        assert_eq!(host.value_hint, ValueHint::Unknown);

        let log_level = arg_by_long(&cmd, "--log-level").unwrap();
        assert_eq!(log_level.short.as_deref(), Some("-l"));

        let tls = arg_by_long(&cmd, "--tls").unwrap();
        assert_eq!(tls.value_hint, ValueHint::Unknown);

        let tlscacert = arg_by_long(&cmd, "--tlscacert").unwrap();
        assert_eq!(tlscacert.value_hint, ValueHint::Unknown);

        let tlscert = arg_by_long(&cmd, "--tlscert").unwrap();
        assert_eq!(tlscert.value_hint, ValueHint::AnyPath);

        let tlskey = arg_by_long(&cmd, "--tlskey").unwrap();
        assert_eq!(tlskey.value_hint, ValueHint::AnyPath);

        let tlsverify = arg_by_long(&cmd, "--tlsverify").unwrap();
        assert_eq!(tlsverify.value_hint, ValueHint::Unknown);

        let version = arg_by_long(&cmd, "--version").unwrap();
        assert_eq!(version.short.as_deref(), Some("-v"));
    }

    #[test]
    fn test_npm_help() {
        let cmd = parse_test_help("npm");
        let subs = subcommand_names(&cmd);
        let expected_subs = vec![
            "access",
            "adduser",
            "audit",
            "bugs",
            "cache",
            "ci",
            "completion",
            "config",
            "dedupe",
            "deprecate",
            "diff",
            "dist-tag",
            "docs",
            "doctor",
            "edit",
            "exec",
            "explain",
            "explore",
            "find-dupes",
            "fund",
            "get",
            "help",
            "hook",
            "init",
            "install",
            "install-ci-test",
            "install-test",
            "link",
            "ll",
            "login",
            "logout",
            "ls",
            "org",
            "outdated",
            "owner",
            "pack",
            "ping",
            "pkg",
            "prefix",
            "profile",
            "prune",
            "publish",
            "query",
            "rebuild",
            "repo",
            "restart",
            "root",
            "run-script",
            "search",
            "set",
            "shrinkwrap",
            "star",
            "stars",
            "start",
            "stop",
            "team",
            "test",
            "token",
            "uninstall",
            "unpublish",
            "unstar",
            "update",
            "version",
            "view",
            "whoami",
        ];
        for sub in expected_subs {
            assert!(subs.contains(&sub), "Missing subcommand: {}", sub);
        }
    }

    #[test]
    fn test_systemctl_help() {
        let cmd = parse_test_help("systemctl");
        let subs = subcommand_names(&cmd);
        let expected_subs = vec![
            "list-units",
            "start",
            "stop",
            "status",
            "enable",
            "disable",
            "daemon-reload",
            "restart",
            "reload",
            "is-active",
        ];
        for sub in expected_subs {
            assert!(subs.contains(&sub), "Missing subcommand: {}", sub);
        }

        let host = arg_by_long(&cmd, "--host").unwrap();
        assert_eq!(host.short.as_deref(), Some("-H"));
        assert_eq!(host.value_hint, ValueHint::Hostname);

        let machine = arg_by_long(&cmd, "--machine").unwrap();
        assert_eq!(machine.short.as_deref(), Some("-M"));

        let property = arg_by_long(&cmd, "--property").unwrap();
        assert_eq!(property.short.as_deref(), Some("-p"));

        let all = arg_by_long(&cmd, "--all").unwrap();
        assert_eq!(all.short.as_deref(), Some("-a"));

        let full = arg_by_long(&cmd, "--full").unwrap();
        assert_eq!(full.short.as_deref(), Some("-l"));

        let recursive = arg_by_long(&cmd, "--recursive").unwrap();
        assert_eq!(recursive.short.as_deref(), Some("-r"));

        let root = arg_by_long(&cmd, "--root").unwrap();
        assert_eq!(root.value_hint, ValueHint::DirPath);

        let lines = arg_by_long(&cmd, "--lines").unwrap();
        assert_eq!(lines.short.as_deref(), Some("-n"));
    }

    #[test]
    fn test_apt_help() {
        let cmd = parse_test_help("apt");
        let subs = subcommand_names(&cmd);
        let expected_subs = vec![
            "list",
            "search",
            "show",
            "install",
            "reinstall",
            "remove",
            "autoremove",
            "update",
            "upgrade",
            "full-upgrade",
            "edit-sources",
            "satisfy",
        ];
        for sub in expected_subs {
            assert!(subs.contains(&sub), "Missing subcommand: {}", sub);
        }
    }

    #[test]
    fn test_pip_help() {
        let cmd = parse_test_help("pip");
        let subs = subcommand_names(&cmd);
        let expected_subs = vec![
            "install",
            "uninstall",
            "list",
            "show",
            "config",
            "download",
            "freeze",
            "check",
            "search",
            "cache",
        ];
        for sub in expected_subs {
            assert!(subs.contains(&sub), "Missing subcommand: {}", sub);
        }

        let verbose = arg_by_long(&cmd, "--verbose").unwrap();
        assert_eq!(verbose.short.as_deref(), Some("-v"));

        let version = arg_by_long(&cmd, "--version").unwrap();
        assert_eq!(version.short.as_deref(), Some("-V"));

        let quiet = arg_by_long(&cmd, "--quiet").unwrap();
        assert_eq!(quiet.short.as_deref(), Some("-q"));

        let log = arg_by_long(&cmd, "--log").unwrap();
        assert_eq!(log.value_hint, ValueHint::AnyPath);

        let proxy = arg_by_long(&cmd, "--proxy").unwrap();
        assert_eq!(proxy.value_hint, ValueHint::Unknown);

        let trusted_host = arg_by_long(&cmd, "--trusted-host").unwrap();
        assert_eq!(trusted_host.value_hint, ValueHint::Hostname);

        let cert = arg_by_long(&cmd, "--cert").unwrap();
        assert_eq!(cert.value_hint, ValueHint::AnyPath);

        let cache_dir = arg_by_long(&cmd, "--cache-dir").unwrap();
        assert_eq!(cache_dir.value_hint, ValueHint::DirPath);
    }

    #[test]
    fn test_go_help() {
        let cmd = parse_test_help("go");
        let subs = subcommand_names(&cmd);
        let expected_subs = vec![
            "build", "run", "test", "fmt", "get", "version", "clean", "doc", "env", "fix",
            "generate", "install", "list", "mod", "work", "tool", "vet",
        ];
        for sub in expected_subs {
            assert!(subs.contains(&sub), "Missing subcommand: {}", sub);
        }
    }

    #[test]
    fn test_gh_help() {
        let cmd = parse_test_help("gh");
        let subs = subcommand_names(&cmd);
        let expected_subs = vec![
            "auth",
            "pr",
            "repo",
            "issue",
            "run",
            "gist",
            "alias",
            "api",
            "completion",
            "config",
        ];
        for sub in expected_subs {
            assert!(subs.contains(&sub), "Missing subcommand: {}", sub);
        }

        assert!(long_names(&cmd).contains(&"--help"));
        assert!(long_names(&cmd).contains(&"--version"));
    }

    #[test]
    fn test_curl_help() {
        let cmd = parse_test_help("curl");
        let longs = long_names(&cmd);
        assert!(longs.contains(&"--data"));
        assert!(longs.contains(&"--fail"));
        assert!(longs.contains(&"--output"));
        assert!(longs.contains(&"--user"));

        let output_arg = arg_by_long(&cmd, "--output").unwrap();
        assert_eq!(output_arg.short.as_deref(), Some("-o"));
        assert_eq!(output_arg.value_hint, ValueHint::FilePath);
    }

    #[test]
    fn test_tar_help() {
        let cmd = parse_test_help("tar");
        let longs = long_names(&cmd);
        assert!(longs.contains(&"--create"));
        assert!(longs.contains(&"--extract"));
        assert!(longs.contains(&"--list"));
        assert!(longs.contains(&"--file"));

        let file_arg = arg_by_long(&cmd, "--file").unwrap();
        assert_eq!(file_arg.short.as_deref(), Some("-f"));
    }
}
