//! Parse a `--help` string into a [`Command`] structure.
//!
//! The entry point is [`parse_help`].  It tries to identify which help format
//! the text comes from (clap, Python argparse, or an unknown generic format)
//! and dispatches to the appropriate sub-parser.

// ──────────────────────────────────────────────────────────────────────────────
// Public data structures
// ──────────────────────────────────────────────────────────────────────────────

/// A single command-line argument / flag.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Arg {
    /// Long flag name, e.g. `--verbose`.
    pub long: Option<String>,
    /// Short flag name, e.g. `-v`.
    pub short: Option<String>,
    /// Human-readable description.
    pub description: Option<String>,
    /// Meta-variable / value type hint (e.g. `<PATH>`, `<N>`).
    pub value_type: Option<String>,
    /// Number of values accepted (e.g. `*`, `+`, `?`, or a count like `"1"`).
    pub num_args: Option<String>,
}

/// A parsed command (or sub-command).
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Command {
    /// Name of the command, if known.
    pub name: Option<String>,
    /// Author / maintainer information, if present.
    pub author: Option<String>,
    /// Short description / about line.
    pub description: Option<String>,
    /// Recognised arguments / flags.
    pub args: Vec<Arg>,
    /// Recognised sub-commands.
    pub subcommands: Vec<Command>,
}

// ──────────────────────────────────────────────────────────────────────────────
// Format detection
// ──────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum HelpFormat {
    /// Output generated by [clap](https://docs.rs/clap) (Rust).
    Clap,
    /// Output generated by Python's `argparse` module.
    Argparse,
    /// Unknown / generic format.
    Generic,
}

fn detect_format(help: &str) -> HelpFormat {
    // clap outputs a "Usage:" line (capital U) and uses long option descriptions
    // indented underneath the flag, separated by an empty line.
    let has_usage = help.contains("Usage:");
    let has_commands_section = help.contains("\nCommands:\n") || help.contains("\nSubcommands:\n");
    // argparse always prints "usage:" (lowercase) and "optional arguments:" or
    // "options:" sections.
    let has_positional = help.contains("positional arguments:");
    let has_optional = help.contains("optional arguments:") || help.contains("options:");

    if has_positional || (has_optional && !has_commands_section) {
        // Pure argparse output never has a "Commands:" section.
        HelpFormat::Argparse
    } else if has_usage || has_commands_section {
        HelpFormat::Clap
    } else {
        HelpFormat::Generic
    }
}

// ──────────────────────────────────────────────────────────────────────────────
// Public entry point
// ──────────────────────────────────────────────────────────────────────────────

/// Parse a `--help` string into a [`Command`] with the best fidelity possible.
///
/// The function auto-detects whether the string was produced by *clap*,
/// Python *argparse*, or an unknown tool, and dispatches accordingly.
pub fn parse_help(help: &str) -> Command {
    match detect_format(help) {
        HelpFormat::Clap => parse_help_clap(help),
        HelpFormat::Argparse => parse_help_argparse(help),
        HelpFormat::Generic => parse_help_generic(help),
    }
}

// ──────────────────────────────────────────────────────────────────────────────
// Helper utilities
// ──────────────────────────────────────────────────────────────────────────────

/// Leading-space count for a line (tabs count as 1).
fn indent_of(line: &str) -> usize {
    line.chars().take_while(|c| *c == ' ' || *c == '\t').count()
}

/// Try to parse a flag token like `-v`, `--verbose`, or `--output <FILE>`.
/// Returns `(short, long, value_type)`.
fn parse_flag_tokens(token: &str) -> (Option<String>, Option<String>, Option<String>) {
    // Split on commas / whitespace to handle "-v, --verbose <FILE>"
    let mut short = None;
    let mut long = None;
    let mut value_type = None;

    // Tokenise: split on ", " first, then whitespace
    let pieces: Vec<&str> = token.split_whitespace().collect();
    for piece in &pieces {
        if piece.starts_with("--") {
            // May be "--flag" or "--flag=<VAL>"
            if let Some((flag, val)) = piece.split_once('=') {
                long = Some(flag.trim_end_matches(',').to_string());
                value_type = Some(val.trim_matches(|c| c == '<' || c == '>').to_string());
            } else {
                long = Some(piece.trim_end_matches(',').to_string());
            }
        } else if piece.starts_with('-') && piece.len() <= 3 {
            // Short flag like -v or -v,
            short = Some(piece.trim_end_matches(',').to_string());
        } else if piece.starts_with('<') || piece.starts_with('[') {
            // Meta-variable — only capture the first one found so that description
            // text like `[default: 10]` does not overwrite an already-parsed hint.
            if value_type.is_none() {
                value_type = Some(
                    piece
                        .trim_matches(|c| c == '<' || c == '>' || c == '[' || c == ']')
                        .to_string(),
                );
            }
        }
    }
    (short, long, value_type)
}

/// Collect continuation lines: lines whose indent > `base_indent` (or blank).
/// Returns the combined description string.
fn collect_continuation<'a>(
    lines: &'a [&'a str],
    start: usize,
    base_indent: usize,
) -> (String, usize) {
    let mut desc_parts = Vec::new();
    let mut i = start;
    while i < lines.len() {
        let line = lines[i];
        if line.trim().is_empty() {
            // blank line ends the block
            break;
        }
        let ind = indent_of(line);
        if ind <= base_indent {
            break;
        }
        // A deeper-indented line that starts with `-` is another flag entry,
        // not description text (e.g. cargo mixes indent levels in Options:).
        if line.trim().starts_with('-') {
            break;
        }
        desc_parts.push(line.trim().to_string());
        i += 1;
    }
    (desc_parts.join(" "), i)
}

// ──────────────────────────────────────────────────────────────────────────────
// clap parser
// ──────────────────────────────────────────────────────────────────────────────

/// Parse clap-style `--help` output.
///
/// Typical structure:
/// ```text
/// <description>
///
/// Usage: <name> [OPTIONS] [COMMAND]
///
/// Commands:
///   subcommand1  Short description
///   subcommand2  Short description
///
/// Arguments:
///   [ARG]  description
///
/// Options:
///       --flag <VALUE>
///           Long description
///   -h, --help
///           Print help
/// ```
pub fn parse_help_clap(help: &str) -> Command {
    let lines: Vec<&str> = help.lines().collect();
    let mut cmd = Command::default();

    // Extract name from "Usage:" line; handles both "Usage: name ..." (clap/commander)
    // and "Usage:\n  name ..." (cobra/docopt) styles.
    if let Some(usage_pos) = lines
        .iter()
        .position(|l| l.trim_start().starts_with("Usage:"))
    {
        let after = lines[usage_pos].trim_start_matches(|c: char| c.is_whitespace());
        let after = after.strip_prefix("Usage:").unwrap_or(after).trim();
        if let Some(name_part) = after.split_whitespace().next() {
            // Standard "Usage: name ..." form.
            cmd.name = Some(name_part.to_string());
        } else {
            // Cobra/docopt form: "Usage:" is alone on its own line; name is on the next.
            for next_line in &lines[usage_pos + 1..] {
                let t = next_line.trim();
                if !t.is_empty() {
                    if let Some(name_part) = t.split_whitespace().next() {
                        cmd.name = Some(name_part.to_string());
                    }
                    break;
                }
            }
        }
    }

    // First non-empty line before "Usage:" is the description.
    let usage_pos = lines
        .iter()
        .position(|l| l.trim_start().starts_with("Usage:"))
        .unwrap_or(0);
    for line in &lines[..usage_pos] {
        let t = line.trim();
        if !t.is_empty() {
            cmd.description = Some(t.to_string());
            break;
        }
    }

    // Section parsing.
    let mut i = 0;
    while i < lines.len() {
        let trimmed = lines[i].trim();

        // ── Commands / Subcommands section ──────────────────────────────────
        if trimmed == "Commands:" || trimmed == "Subcommands:" || trimmed == "Available Commands:" {
            i += 1;
            while i < lines.len() {
                let line = lines[i];
                if line.trim().is_empty() {
                    i += 1;
                    break;
                }
                // Guard: a non-indented non-empty line is a new section header.
                if indent_of(line) == 0 && !line.trim().is_empty() {
                    break;
                }
                let trimmed_line = line.trim();
                // Format: "  subname  Short description"
                let mut parts = trimmed_line.splitn(2, "  ");
                let sub_name = parts.next().unwrap_or("").trim().to_string();
                let sub_desc = parts.next().map(|s| s.trim().to_string());
                if !sub_name.is_empty() {
                    cmd.subcommands.push(Command {
                        name: Some(sub_name),
                        description: sub_desc,
                        ..Command::default()
                    });
                }
                i += 1;
            }
            continue;
        }

        // ── Options / Arguments / Flags section ────────────────────────────
        if trimmed == "Options:"
            || trimmed == "Arguments:"
            || trimmed == "Flags:"
            || trimmed == "Global Flags:"
            || trimmed == "Global Options:"
        {
            i += 1;
            while i < lines.len() {
                let line = lines[i];
                if line.trim().is_empty() {
                    i += 1;
                    // blank line may separate args but we continue
                    continue;
                }
                // A non-indented non-empty line is a new section header.
                if indent_of(line) == 0 {
                    break;
                }
                let flag_indent = indent_of(line);
                let flag_part = line.trim();

                // Skip pure description continuation lines that are deeper
                // (they belong to the previous arg).
                // We identify flag lines as ones that start with '-' or '['.
                if !flag_part.starts_with('-') && !flag_part.starts_with('[') {
                    i += 1;
                    continue;
                }

                let (short, long, value_type) = parse_flag_tokens(flag_part);
                // Collect description: next lines indented more than flag_indent.
                let (desc, next_i) = collect_continuation(&lines, i + 1, flag_indent);
                i = next_i;

                let num_args = if value_type.is_some() {
                    Some("1".to_string())
                } else {
                    None
                };

                cmd.args.push(Arg {
                    short,
                    long,
                    description: if desc.is_empty() { None } else { Some(desc) },
                    value_type,
                    num_args,
                });
            }
            continue;
        }

        i += 1;
    }

    cmd
}

// ──────────────────────────────────────────────────────────────────────────────
// argparse parser
// ──────────────────────────────────────────────────────────────────────────────

/// Parse Python argparse-style `--help` output.
///
/// Typical structure:
/// ```text
/// usage: script.py [-h] [--flag VALUE] positional
///
/// Description of the program.
///
/// positional arguments:
///   positional   help text
///
/// optional arguments:
///   -h, --help   show this help message and exit
///   --flag VALUE
///                help text for flag
/// ```
pub fn parse_help_argparse(help: &str) -> Command {
    let lines: Vec<&str> = help.lines().collect();
    let mut cmd = Command::default();

    // Command name from "usage:" line.
    if let Some(usage_line) = lines
        .iter()
        .find(|l| l.trim_start().to_lowercase().starts_with("usage:"))
    {
        let after = usage_line
            .trim_start_matches(|c: char| c.is_whitespace())
            .to_lowercase();
        let after = after.strip_prefix("usage:").unwrap_or(&after).trim();
        if let Some(name) = after.split_whitespace().next() {
            cmd.name = Some(name.to_string());
        }
    }

    // Description: first non-empty line after blank line following "usage:".
    let usage_pos = lines
        .iter()
        .position(|l| l.trim_start().to_lowercase().starts_with("usage:"))
        .unwrap_or(0);
    let mut found_blank = false;
    for line in &lines[usage_pos + 1..] {
        if line.trim().is_empty() {
            found_blank = true;
        } else if found_blank {
            let t = line.trim();
            // Don't treat section headers as the description.
            if !t.ends_with(':') {
                cmd.description = Some(t.to_string());
            }
            break;
        }
    }

    // Section parsing.
    let mut i = 0;
    while i < lines.len() {
        let trimmed = lines[i].trim();

        let is_args_section = trimmed == "positional arguments:"
            || trimmed == "optional arguments:"
            || trimmed == "options:"
            || trimmed.starts_with("named arguments:");

        if is_args_section {
            i += 1;
            while i < lines.len() {
                let line = lines[i];
                if line.trim().is_empty() {
                    i += 1;
                    break;
                }
                // Non-indented line → new section.
                if indent_of(line) == 0 && line.trim().ends_with(':') {
                    break;
                }
                let flag_indent = indent_of(line);
                let flag_part = line.trim();

                // argparse flag lines start with '-' for flags or a word for positional.
                let (short, long, value_type) = if flag_part.starts_with('-') {
                    parse_flag_tokens(flag_part)
                } else {
                    // Positional argument: first word is the name.
                    let name_token = flag_part.split_whitespace().next().unwrap_or("");
                    (None, Some(name_token.to_string()), None)
                };

                // Description may be inline (after double-space) or on continuation lines.
                let inline_desc: Option<String> = if let Some(pos) = flag_part.find("  ") {
                    let d = flag_part[pos..].trim();
                    if !d.is_empty() {
                        Some(d.to_string())
                    } else {
                        None
                    }
                } else {
                    None
                };

                let (cont_desc, next_i) = collect_continuation(&lines, i + 1, flag_indent);
                i = next_i;

                let description = match (inline_desc, cont_desc.as_str()) {
                    (Some(d), "") => Some(d),
                    (None, d) if !d.is_empty() => Some(d.to_string()),
                    (Some(d), rest) => Some(format!("{} {}", d, rest)),
                    (None, _) => None,
                };

                let num_args = if value_type.is_some() {
                    Some("1".to_string())
                } else {
                    None
                };

                cmd.args.push(Arg {
                    short,
                    long,
                    description,
                    value_type,
                    num_args,
                });
            }
            continue;
        }

        i += 1;
    }

    cmd
}

// ──────────────────────────────────────────────────────────────────────────────
// Generic / fallback parser
// ──────────────────────────────────────────────────────────────────────────────

/// Fallback parser for unrecognised help formats.
///
/// Uses heuristics:
/// - Lines that start with `-` are treated as argument definitions.
/// - A two-space-separated suffix on such a line is the inline description.
/// - Deeper-indented lines following a flag are appended to its description.
pub fn parse_help_generic(help: &str) -> Command {
    let lines: Vec<&str> = help.lines().collect();
    let mut cmd = Command::default();

    // Try to find a name from the first "usage"/"Usage" line.
    for line in &lines {
        let lower = line.trim().to_lowercase();
        if lower.starts_with("usage:") {
            let after = line
                .trim()
                .trim_start_matches(|c: char| c.is_alphabetic() || c == ':')
                .trim();
            if let Some(name) = after.split_whitespace().next() {
                cmd.name = Some(name.to_string());
                break;
            }
        }
    }

    // Collect description from the first non-empty line if it doesn't look
    // like a flag or section header.
    for line in &lines {
        let t = line.trim();
        if !t.is_empty() && !t.starts_with('-') && !t.to_lowercase().starts_with("usage:") {
            cmd.description = Some(t.to_string());
            break;
        }
    }

    // Scan for argument lines.
    let mut i = 0;
    while i < lines.len() {
        let line = lines[i];
        let flag_part = line.trim();

        if flag_part.starts_with('-') {
            let flag_indent = indent_of(line);
            let (short, long, value_type) = parse_flag_tokens(flag_part);

            let inline_desc: Option<String> = if let Some(pos) = flag_part.find("  ") {
                let d = flag_part[pos..].trim();
                if !d.is_empty() {
                    Some(d.to_string())
                } else {
                    None
                }
            } else {
                None
            };

            let (cont_desc, next_i) = collect_continuation(&lines, i + 1, flag_indent);
            i = next_i;

            let description = match (inline_desc, cont_desc.as_str()) {
                (Some(d), "") => Some(d),
                (None, d) if !d.is_empty() => Some(d.to_string()),
                (Some(d), rest) => Some(format!("{} {}", d, rest)),
                (None, _) => None,
            };

            let num_args = if value_type.is_some() {
                Some("1".to_string())
            } else {
                None
            };

            cmd.args.push(Arg {
                short,
                long,
                description,
                value_type,
                num_args,
            });
            continue;
        }

        i += 1;
    }

    cmd
}

// ──────────────────────────────────────────────────────────────────────────────
// Tests
// ──────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    // ── helpers ──────────────────────────────────────────────────────────────

    /// Returns the long names of all args in `cmd`.
    fn long_names(cmd: &Command) -> Vec<&str> {
        cmd.args.iter().filter_map(|a| a.long.as_deref()).collect()
    }

    /// Returns the short names of all args in `cmd`.
    fn short_names(cmd: &Command) -> Vec<&str> {
        cmd.args.iter().filter_map(|a| a.short.as_deref()).collect()
    }

    /// Returns the names of all sub-commands in `cmd`.
    fn subcommand_names(cmd: &Command) -> Vec<&str> {
        cmd.subcommands
            .iter()
            .filter_map(|s| s.name.as_deref())
            .collect()
    }

    /// Looks up an arg by its long name.
    fn arg_by_long<'a>(cmd: &'a Command, long: &str) -> Option<&'a Arg> {
        cmd.args.iter().find(|a| a.long.as_deref() == Some(long))
    }

    /// Looks up a subcommand by name.
    fn subcommand_by_name<'a>(cmd: &'a Command, name: &str) -> Option<&'a Command> {
        cmd.subcommands
            .iter()
            .find(|s| s.name.as_deref() == Some(name))
    }

    // ── flyline --help (clap) ────────────────────────────────────────────────

    const FLYLINE_HELP: &str = r#"Usage: flyline [OPTIONS] [COMMAND]

Commands:
  agent-mode   Configure AI agent mode.
  create-anim  Create a custom prompt animation.
  set-color    Configure the colour palette.
  key          Manage keybindings.
  help         Print this message or the help of the given subcommand(s)

Options:
      --version
          Show version information

      --dump-logs [<PATH>]
          Dump in-memory logs to file. Optionally specify a PATH; if omitted, a timestamped file is created in the current directory

      --stream-logs <PATH>
          Dump current logs to PATH and append new logs. Use `stderr` to stream to standard error

      --log-level <LEVEL>
          Set the logging level
          
          [possible values: error, warn, info, debug, trace]

      --load-zsh-history [<PATH>]
          Load Zsh history in addition to Bash history. Optionally specify a PATH to the Zsh history file; if omitted, defaults to $HOME/.zsh_history

      --tutorial-mode [<TUTORIAL_MODE>]
          Enable or disable tutorial mode with hints for first-time users. Use `--tutorial-mode false` to disable
          
          [possible values: true, false]

      --show-animations [<SHOW_ANIMATIONS>]
          Show animations
          
          [possible values: true, false]

      --show-inline-history [<SHOW_INLINE_HISTORY>]
          Show inline history suggestions
          
          [possible values: true, false]

      --auto-close-chars [<AUTO_CLOSE_CHARS>]
          Enable automatic closing character insertion (e.g. insert `)` after `(`)
          
          [possible values: true, false]

      --use-term-emulator-cursor [<USE_TERM_EMULATOR_CURSOR>]
          Use the terminal emulator's cursor instead of rendering a custom cursor

      --matrix-animation [<MATRIX_ANIMATION>]
          Run matrix animation in the terminal background
          
          [possible values: true, false]

      --frame-rate <FPS>
          Render frame rate in frames per second (1–120, default 30)

      --mouse-mode <MODE>
          Mouse capture mode (disabled, simple, smart). Default is smart

      --send-shell-integration-codes [<SEND_SHELL_INTEGRATION_CODES>]
          Send shell integration escape codes (OSC 133 / OSC 633)
          
          [possible values: true, false]

  -h, --help
          Print help (see a summary with '-h')

Read more at https://github.com/HalFrgrd/flyline
"#;

    #[test]
    fn test_flyline_help_clap() {
        let cmd = parse_help(FLYLINE_HELP);
        assert_eq!(cmd.name.as_deref(), Some("flyline"));

        // Subcommands and their descriptions.
        let subs = subcommand_names(&cmd);
        assert!(subs.contains(&"agent-mode"));
        assert!(subs.contains(&"create-anim"));
        assert!(subs.contains(&"set-color"));
        assert!(subs.contains(&"key"));
        assert_eq!(
            subcommand_by_name(&cmd, "agent-mode").and_then(|s| s.description.as_deref()),
            Some("Configure AI agent mode.")
        );
        assert_eq!(
            subcommand_by_name(&cmd, "create-anim").and_then(|s| s.description.as_deref()),
            Some("Create a custom prompt animation.")
        );

        // Flag names.
        let longs = long_names(&cmd);
        assert!(longs.contains(&"--version"));
        assert!(longs.contains(&"--dump-logs"));
        assert!(longs.contains(&"--log-level"));
        assert!(longs.contains(&"--frame-rate"));
        assert!(longs.contains(&"--mouse-mode"));
        assert!(longs.contains(&"--help"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-h"));

        // Value types (meta-variable hints).
        assert_eq!(
            arg_by_long(&cmd, "--log-level").and_then(|a| a.value_type.as_deref()),
            Some("LEVEL")
        );
        assert_eq!(
            arg_by_long(&cmd, "--frame-rate").and_then(|a| a.value_type.as_deref()),
            Some("FPS")
        );
        assert_eq!(
            arg_by_long(&cmd, "--mouse-mode").and_then(|a| a.value_type.as_deref()),
            Some("MODE")
        );

        // Descriptions on continuation lines.
        assert_eq!(
            arg_by_long(&cmd, "--version").and_then(|a| a.description.as_deref()),
            Some("Show version information")
        );
        assert!(
            arg_by_long(&cmd, "--log-level")
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("logging level"),
            "description should mention 'logging level'"
        );
    }

    // ── flyline create-anim --help (clap) ────────────────────────────────────

    const FLYLINE_CREATE_ANIM_HELP: &str = r#"Create a custom prompt animation.

Instances of NAME in prompt strings (PS1, RPS1, PS1_FILL) are replaced
with the current animation frame on every render.  Frames may include
ANSI colour sequences written as `\e` (e.g. `\e[33m`).

Examples:
  flyline create-anim --name "MY_ANIMATION" --fps 10  ⣾ ⣷ ⣯ ⣟ ⡿ ⢿ ⣻ ⣽
  flyline create-anim --name "john" --ping-pong --fps 5  '\e[33m\u' '\e[31m\u' '\e[35m\u' '\e[36m\u'

Usage: flyline create-anim [OPTIONS] --name <NAME> [FRAMES]...

Arguments:
  [FRAMES]...
          One or more animation frames (positional).  Use `\e` for the ESC character

Options:
      --name <NAME>
          Name to embed in prompt strings as the animation placeholder

      --fps <FPS>
          Playback speed in frames per second (default: 10)
          
          [default: 10]

      --ping-pong
          Reverse direction at each end instead of wrapping (ping-pong / bounce mode)

  -h, --help
          Print help (see a summary with '-h')
"#;

    #[test]
    fn test_flyline_create_anim_help_clap() {
        let cmd = parse_help(FLYLINE_CREATE_ANIM_HELP);
        assert_eq!(cmd.name.as_deref(), Some("flyline"));
        assert!(
            cmd.description
                .as_deref()
                .unwrap_or("")
                .contains("animation"),
            "description should mention animation"
        );

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--name"));
        assert!(longs.contains(&"--fps"));
        assert!(longs.contains(&"--ping-pong"));
        assert!(longs.contains(&"--help"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-h"));

        // Value types.
        assert_eq!(
            arg_by_long(&cmd, "--name").and_then(|a| a.value_type.as_deref()),
            Some("NAME")
        );
        assert_eq!(
            arg_by_long(&cmd, "--fps").and_then(|a| a.value_type.as_deref()),
            Some("FPS")
        );

        // Descriptions on continuation lines.
        assert!(
            arg_by_long(&cmd, "--name")
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("animation placeholder"),
            "description should mention 'animation placeholder'"
        );
        assert!(
            arg_by_long(&cmd, "--fps")
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("frames per second"),
            "description should mention 'frames per second'"
        );
        assert!(
            arg_by_long(&cmd, "--ping-pong")
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("Reverse direction"),
            "description should mention 'Reverse direction'"
        );
    }

    // ── cargo --help (clap) ──────────────────────────────────────────────────

    const CARGO_HELP: &str = r#"Rust's package manager

Usage: cargo [+toolchain] [OPTIONS] [COMMAND]
       cargo [+toolchain] [OPTIONS] -Zscript [ARGS]...

Options:
  -V, --version              Print version info and exit
      --list                 List installed commands
      --explain <CODE>       Run `rustc --explain CODE`
  -v, --verbose              Use verbose output (-vv very verbose/build.rs output)
  -q, --quiet                Do not print cargo log messages
      --color <WHEN>         Coloring: auto, always, never
  -C <DIRECTORY>             Change to DIRECTORY before doing anything (nightly-only)
      --frozen               Require Cargo.lock and cache are up to date
      --locked               Require Cargo.lock is up to date
      --offline              Run without accessing the network
      --config <KEY=VALUE>   Override a configuration value
  -Z <FLAG>                  Unstable (nightly-only) flags to Cargo, see 'cargo -Z help' for details
  -h, --help                 Print help

Some common cargo commands are (see all commands with --list):
    build, b    Compile the current package
    check, c    Analyze the current package and report errors, but don't build object files
    clean       Remove the generated artifacts
    doc, d      Build this package's and its dependencies' documentation
    run, r      Run a binary or example of the local package
    test, t     Run the tests
    bench       Run the benchmarks
    update      Update dependencies listed in Cargo.lock
    search      Search registry for crates
    publish     Publish this package to the registry
    add         Add dependencies to a manifest file
    remove      Remove dependencies from a manifest file

See 'cargo help <command>' for more information on a specific command.
"#;

    #[test]
    fn test_cargo_help_clap() {
        let cmd = parse_help(CARGO_HELP);
        assert_eq!(cmd.name.as_deref(), Some("cargo"));

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--version"));
        assert!(longs.contains(&"--verbose"));
        assert!(longs.contains(&"--quiet"));
        assert!(longs.contains(&"--explain"));
        assert!(longs.contains(&"--color"));
        assert!(longs.contains(&"--help"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-V"));
        assert!(shorts.contains(&"-v"));
        assert!(shorts.contains(&"-h"));

        // Value types inferred from inline meta-variables.
        assert_eq!(
            arg_by_long(&cmd, "--explain").and_then(|a| a.value_type.as_deref()),
            Some("CODE")
        );
        assert_eq!(
            arg_by_long(&cmd, "--color").and_then(|a| a.value_type.as_deref()),
            Some("WHEN")
        );
    }

    // ── python --help (argparse-like, but actually custom) ───────────────────

    const PYTHON_HELP: &str = r#"usage: python3 [option] ... [-c cmd | -m mod | file | -] [arg] ...
Options and arguments (and corresponding environment variables):
-b     : issue warnings about str(bytes_instance), str(bytearray_instance)
         and comparing bytes/bytearray with str. (-bb: issue errors)
-B     : don't write .pyc files on import; also PYTHONDONTWRITEBYTECODE=x
-c cmd : program passed in as string (terminates option list)
-d     : debug output from parser; also PYTHONDEBUG=x
-E     : ignore PYTHON* environment variables (such as PYTHONPATH)
-h     : print this help message and exit (also --help)
-i     : inspect interactively after running script; forces a prompt even
         if stdin does not appear to be a terminal; also PYTHONINSPECT=x
-I     : isolate Python from the user's environment (implies -E and -s)
-m mod : run library module as a script (terminates option list)
-O     : remove assert and __debug__-dependent statements; add .opt-1 before
         .pyc extension; also PYTHONOPTIMIZE=x
-OO    : do -O changes and also discard docstrings; add .opt-2 before
         .pyc extension
-q     : don't print version and copyright messages on interactive startup
-s     : don't add user site directory to sys.path; also PYTHONNOUSERSITE=x
-S     : don't imply 'import site' on initialization
-u     : force the stdout and stderr streams to be unbuffered;
         this option has no effect on stdin; also PYTHONASYNCIOGENIGNORE=x
-v     : verbose (trace import statements); also PYTHONVERBOSE=x;
         can be supplied multiple times to increase verbosity
-V     : print the Python version number and exit (also --version)
         --version :  print just the version number to stdout and exit
-W arg : warning control; arg is action:message:category:module:lineno
         also PYTHONWARNINGS=x
-x     : skip first line of source, allowing use of non-Unix forms of #!cmd
-X opt : set implementation-specific option
--check-hash-based-pycs always|default|never:
    control how Python invalidates hash-based .pyc files
file   : program read from script file
-      : program read from stdin (default; interactive mode if a tty)
arg ...: arguments passed to program in sys.argv[1:]

Other environment variables:
PYTHONSTARTUP: file executed on interactive startup (no default)
PYTHONPATH   : ':'-separated list of directories prefixed to the
               default module search path.  The result is sys.path.
"#;

    #[test]
    fn test_python_help_generic() {
        // python --help doesn't follow argparse or clap exactly; falls through to generic.
        let cmd = parse_help(PYTHON_HELP);
        assert_eq!(cmd.name.as_deref(), Some("python3"));

        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-h"));
        assert!(shorts.contains(&"-v"));
        assert!(shorts.contains(&"-V"));
        assert!(shorts.contains(&"-q"));

        // Descriptions captured inline (separator is ` : `).
        assert!(
            cmd.args
                .iter()
                .find(|a| a.short.as_deref() == Some("-h"))
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("help message"),
            "description should mention 'help message'"
        );
    }

    // ── Python argparse example ───────────────────────────────────────────────

    const ARGPARSE_EXAMPLE: &str = r#"usage: prog.py [-h] [--foo FOO] bar

A sample argparse program.

positional arguments:
  bar          the bar argument

optional arguments:
  -h, --help   show this help message and exit
  --foo FOO    the foo value
"#;

    #[test]
    fn test_argparse_example() {
        let cmd = parse_help(ARGPARSE_EXAMPLE);
        assert_eq!(cmd.name.as_deref(), Some("prog.py"));
        assert!(
            cmd.description
                .as_deref()
                .unwrap_or("")
                .contains("argparse"),
            "description should mention argparse"
        );

        let longs = long_names(&cmd);
        assert!(longs.contains(&"bar"));
        assert!(longs.contains(&"--foo"));
        assert!(longs.contains(&"--help"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-h"));

        // Inline descriptions captured by the argparse parser.
        assert!(
            arg_by_long(&cmd, "bar")
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("bar argument"),
            "description should mention 'bar argument'"
        );
        assert!(
            arg_by_long(&cmd, "--foo")
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("foo value"),
            "description should mention 'foo value'"
        );
    }

    // ── Python argparse with subparsers ──────────────────────────────────────

    const ARGPARSE_SUBPARSERS: &str = r#"usage: myapp [-h] {init,run,stop} ...

My Application

positional arguments:
  {init,run,stop}
    init           Initialize the project
    run            Run the application
    stop           Stop the application

optional arguments:
  -h, --help       show this help message and exit
  --verbose        Enable verbose output
"#;

    #[test]
    fn test_argparse_subparsers() {
        let cmd = parse_help(ARGPARSE_SUBPARSERS);
        assert_eq!(cmd.name.as_deref(), Some("myapp"));
        assert!(
            cmd.description.as_deref().unwrap_or("").contains("My"),
            "description should mention 'My'"
        );

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--help"));
        assert!(longs.contains(&"--verbose"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-h"));

        // Inline description on --verbose.
        assert!(
            arg_by_long(&cmd, "--verbose")
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("verbose output"),
            "description should mention 'verbose output'"
        );
    }

    // ── Click (Python) ────────────────────────────────────────────────────────

    const CLICK_HELP: &str = r#"Usage: cli [OPTIONS] COMMAND [ARGS]...

  A simple CLI built with Click.

Options:
  --name TEXT      The person to greet.
  --count INTEGER  Number of greetings.  [default: 1]
  -v, --verbose    Enable verbose output.
  --help           Show this message and exit.

Commands:
  hello    Greet someone.
  goodbye  Say goodbye.
"#;

    #[test]
    fn test_click_help() {
        let cmd = parse_help(CLICK_HELP);
        assert_eq!(cmd.name.as_deref(), Some("cli"));

        let subs = subcommand_names(&cmd);
        assert!(subs.contains(&"hello"));
        assert!(subs.contains(&"goodbye"));

        // Subcommand descriptions.
        assert_eq!(
            subcommand_by_name(&cmd, "hello").and_then(|s| s.description.as_deref()),
            Some("Greet someone.")
        );
        assert_eq!(
            subcommand_by_name(&cmd, "goodbye").and_then(|s| s.description.as_deref()),
            Some("Say goodbye.")
        );

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--name"));
        assert!(longs.contains(&"--count"));
        assert!(longs.contains(&"--verbose"));
        assert!(longs.contains(&"--help"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-v"));
    }

    // ── argh (Python) ─────────────────────────────────────────────────────────

    const ARGH_HELP: &str = r#"usage: myapp [-h] [--verbose] name

A program using argh.

positional arguments:
  name         the name argument

optional arguments:
  -h, --help   show this help message and exit
  --verbose    enable verbose output
"#;

    #[test]
    fn test_argh_help() {
        let cmd = parse_help(ARGH_HELP);
        assert_eq!(cmd.name.as_deref(), Some("myapp"));
        assert!(
            cmd.description.as_deref().unwrap_or("").contains("argh"),
            "description should mention argh"
        );

        let longs = long_names(&cmd);
        assert!(longs.contains(&"name"));
        assert!(longs.contains(&"--help"));
        assert!(longs.contains(&"--verbose"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-h"));

        // Inline descriptions from argparse format.
        assert!(
            arg_by_long(&cmd, "name")
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("name argument"),
            "description should mention 'name argument'"
        );
        assert!(
            arg_by_long(&cmd, "--verbose")
                .and_then(|a| a.description.as_deref())
                .unwrap_or("")
                .contains("verbose output"),
            "description should mention 'verbose output'"
        );
    }

    // ── yargs (JavaScript) ────────────────────────────────────────────────────

    const YARGS_HELP: &str = r#"my-cli [options]

Commands:
  serve  Start the development server
  build  Build the project for production
  test   Run the test suite

Options:
      --help     Show help                 [boolean]
      --version  Show version number       [boolean]
  -p, --port     Port to listen on         [number]
"#;

    #[test]
    fn test_yargs_help() {
        let cmd = parse_help(YARGS_HELP);
        // No "Usage:" line in this yargs output; name is not extracted.
        let subs = subcommand_names(&cmd);
        assert!(subs.contains(&"serve"));
        assert!(subs.contains(&"build"));
        assert!(subs.contains(&"test"));

        // Subcommand descriptions.
        assert!(
            subcommand_by_name(&cmd, "serve")
                .and_then(|s| s.description.as_deref())
                .unwrap_or("")
                .contains("development server"),
            "description should mention 'development server'"
        );
        assert!(
            subcommand_by_name(&cmd, "build")
                .and_then(|s| s.description.as_deref())
                .unwrap_or("")
                .contains("production"),
            "description should mention 'production'"
        );

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--help"));
        assert!(longs.contains(&"--version"));
        assert!(longs.contains(&"--port"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-p"));
    }

    // ── commander (JavaScript) ────────────────────────────────────────────────

    const COMMANDER_HELP: &str = r#"Usage: program [options] [command]

Options:
  -V, --version  output the version number
  -h, --help     display help for command

Commands:
  start          Start the server
  stop           Stop the server
  status         Show the server status
"#;

    #[test]
    fn test_commander_help() {
        let cmd = parse_help(COMMANDER_HELP);
        assert_eq!(cmd.name.as_deref(), Some("program"));

        let subs = subcommand_names(&cmd);
        assert!(subs.contains(&"start"));
        assert!(subs.contains(&"stop"));
        assert!(subs.contains(&"status"));

        // Subcommand descriptions.
        assert_eq!(
            subcommand_by_name(&cmd, "start").and_then(|s| s.description.as_deref()),
            Some("Start the server")
        );
        assert_eq!(
            subcommand_by_name(&cmd, "stop").and_then(|s| s.description.as_deref()),
            Some("Stop the server")
        );

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--version"));
        assert!(longs.contains(&"--help"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-V"));
        assert!(shorts.contains(&"-h"));
    }

    // ── cobra (Go) ────────────────────────────────────────────────────────────

    const COBRA_HELP: &str = r#"A brief description of your application.

Usage:
  myapp [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  help        Help about any command
  serve       Start the server
  version     Print the version number

Flags:
  -h, --help     help for myapp
  -t, --toggle   Help message for toggle

Global Flags:
      --config string      config file (default "$HOME/.myapp.yaml")
      --log-level string   Log level (default "info")

Use "myapp [command] --help" for more information about a command.
"#;

    #[test]
    fn test_cobra_help() {
        let cmd = parse_help(COBRA_HELP);
        assert_eq!(cmd.name.as_deref(), Some("myapp"));
        assert!(
            cmd.description
                .as_deref()
                .unwrap_or("")
                .contains("application"),
            "description should mention application"
        );

        let subs = subcommand_names(&cmd);
        assert!(subs.contains(&"serve"));
        assert!(subs.contains(&"version"));

        // Subcommand descriptions.
        assert_eq!(
            subcommand_by_name(&cmd, "serve").and_then(|s| s.description.as_deref()),
            Some("Start the server")
        );
        assert!(
            subcommand_by_name(&cmd, "completion")
                .and_then(|s| s.description.as_deref())
                .unwrap_or("")
                .contains("autocompletion"),
            "description should mention 'autocompletion'"
        );

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--help"));
        assert!(longs.contains(&"--toggle"));
        assert!(longs.contains(&"--config"));
        assert!(longs.contains(&"--log-level"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-h"));
        assert!(shorts.contains(&"-t"));
    }

    // ── docopt (Python) ───────────────────────────────────────────────────────

    const DOCOPT_HELP: &str = r#"Usage:
  naval_fate ship <name> move <x> <y> [--speed=<kn>]
  naval_fate ship shoot <x> <y>
  naval_fate mine (set|remove) <x> <y> [--moored|--drifting]
  naval_fate (-h | --help)
  naval_fate --version

Options:
  -h --help     Show this screen.
  --version     Show version.
  --speed=<kn>  Speed in knots [default: 10].
  --moored      Moored (anchored) mine.
  --drifting    Drifting mine.
"#;

    #[test]
    fn test_docopt_help() {
        let cmd = parse_help(DOCOPT_HELP);
        // Name extracted from the first usage pattern line.
        assert_eq!(cmd.name.as_deref(), Some("naval_fate"));

        let longs = long_names(&cmd);
        assert!(longs.contains(&"--help"));
        assert!(longs.contains(&"--version"));
        assert!(longs.contains(&"--speed"));
        assert!(longs.contains(&"--moored"));
        assert!(longs.contains(&"--drifting"));
        let shorts = short_names(&cmd);
        assert!(shorts.contains(&"-h"));

        // --speed=<kn> carries a value-type hint.
        assert_eq!(
            arg_by_long(&cmd, "--speed").and_then(|a| a.value_type.as_deref()),
            Some("kn")
        );
    }
}
