name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

concurrency:
  group: ci
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  build-ubuntu-1604:
    name: Build and test on Ubuntu 16.04
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/bake-action@v6
        with:
          files: docker/docker-bake.hcl
          targets: extract-artifact
          set: |
            extract-artifact.output=type=local,dest=${{ runner.temp }}/docker/build
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max

      - name: Save built library artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-flyline-library
          path: ${{ runner.temp }}/docker/build/libflyline.so


  run-library-tests:
    name: Run library tests
    needs: build-ubuntu-1604
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run tests
        # running the tests by building an image is a cache friendly way to do it
        # if we build a container, the previous step would need to have exported the image to docker
        # which is slow
        uses: docker/bake-action@v6
        with:
          files: docker/docker-bake.hcl
          targets: lib-tests
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max

  bash-integration-tests:
    name: Bash integration tests using built library
    runs-on: ubuntu-latest
    needs:
      - build-ubuntu-1604
    strategy:
      fail-fast: false
      matrix:
        include:
          - { bash_version: "4.4-rc1",  bash_version_slug: "4_4-rc1"  }
          - { bash_version: "4.4.18",   bash_version_slug: "4_4_18"   }
          - { bash_version: "5.0",      bash_version_slug: "5_0"      }
          - { bash_version: "5.1.16",   bash_version_slug: "5_1_16"   }
          - { bash_version: "5.2",      bash_version_slug: "5_2"      }
          - { bash_version: "5.3",      bash_version_slug: "5_3"      }
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Run integration tests
        uses: docker/bake-action@v6
        with:
          files: docker/docker-bake.hcl
          targets: bash-integration-test-${{ matrix.bash_version_slug }}
          set: |
            specific-bash-version-${{ matrix.bash_version_slug }}.cache-from=type=registry,ref=ghcr.io/${{ env.OWNER_LC }}/bash-${{ matrix.bash_version }}:cache
            specific-bash-version-${{ matrix.bash_version_slug }}.cache-to=type=registry,ref=ghcr.io/${{ env.OWNER_LC }}/bash-${{ matrix.bash_version }}:cache,mode=min
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max

  tab-completion-tests:
    name: Test tab completion using built library
    needs: build-ubuntu-1604
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run tab completion tests
        uses: docker/bake-action@v6
        with:
          files: docker/docker-bake.hcl
          targets: tab-completion-tests
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
