name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-ubuntu-1604:
    name: Build and test on Ubuntu 16.04
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/bake-action@v6
        with:
          files: docker/docker-bake.hcl
          source: .
          targets: extract-artifact
          set: |
            extract-artifact.output=type=local,dest=${{ runner.temp }}/docker/build
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max

      - name: Save built library artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-flyline-library
          path: ${{ runner.temp }}/docker/build/libflyline.so


  run-library-tests:
    name: Run library tests
    needs: build-ubuntu-1604
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run tests
        # running the tests by building an image is a cache friendly way to do it
        # if we build a container, the previous step would need to have exported the image to docker
        # which is slow
        uses: docker/bake-action@v6
        with:
          files: docker/docker-bake.hcl
          source: .
          targets: lib-tests
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
      

  bash-integration-tests:
    name: Test bash_${{ matrix.bash_version }} using built library
    needs: build-ubuntu-1604
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        bash_version: [ "4.4-rc1", "4.4.18", "5.0", "5.1.16", "5.2", "5.3"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run integration tests
        uses: docker/bake-action@v6
        with:
          files: docker/docker-bake.hcl
          source: .
          targets: bash-integration-test
          set: |
            bash-integration-test.args.BASH_VERSION=${{ matrix.bash_version }}
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max

  tab-completion-tests:
    name: Test tab completion using built library
    needs: build-ubuntu-1604
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run tab completion tests
        uses: docker/bake-action@v6
        with:
          files: docker/docker-bake.hcl
          source: .
          targets: tab-completion-tests
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
